import org.gradle.jvm.toolchain.JavaLanguageVersion
import java.nio.file.Files
import java.nio.file.StandardCopyOption

plugins {
    java
    idea
}

val asmVersion = "9.10.1"

subprojects {
    configurations.all {
        resolutionStrategy {
            force(
                "org.ow2.asm:asm:$asmVersion",
                "org.ow2.asm:asm-commons:$asmVersion",
                "org.ow2.asm:asm-tree:$asmVersion",
                "org.ow2.asm:asm-analysis:$asmVersion",
                "org.ow2.asm:asm-util:$asmVersion"
            )
        }
    }
}

group = "org.veltismc"
version = "1.0.0-SNAPSHOT"

// ---------------------------------------------------------------------------
// Minecraft pipeline configuration
//
// The development workspace lives at build/minecraft/<minecraftVersion>/,
// laid out by patch-engine's VeltisWorkspace. There are no temporary or
// per-run directories anywhere: every step reads and writes fixed, named
// locations, and `build/` is where a build's generated state belongs — the
// directory `./gradlew clean` already knows how to remove.
//
// A server installation uses a different layout (Vanilla/<v> and Veltis/<v>
// beside the server, with its work tree in the system temporary directory);
// this is the contributor's one.
// ---------------------------------------------------------------------------
val minecraftVersion = providers.gradleProperty("minecraftVersion")
    .orElse("26.3").get()

/**
 * How many targets the patcher applies in parallel. One target is one task, so
 * a patch set with fewer targets than workers simply uses fewer threads. Bounded
 * on purpose: the pool is sized from this, never from the machine, so a build
 * behaves the same on a laptop and on CI.
 */
val patchWorkers = providers.gradleProperty("patchWorkers")
    .map { it.toInt() }
    .orElse(maxOf(1, Runtime.getRuntime().availableProcessors() - 1))
    .get()

val workspaceDir = layout.projectDirectory.dir("build/minecraft/$minecraftVersion")
val vanillaDir = workspaceDir.dir("vanilla")
val metadataDir = workspaceDir.dir("metadata")
val librariesDir = workspaceDir.dir("libraries")
val sourceDir = workspaceDir.dir("source")
val patchedDir = workspaceDir.dir("patched")
val classesDir = workspaceDir.dir("classes")
val resourcesDir = workspaceDir.dir("resources")
val buildStateDir = workspaceDir.dir("build")
val patchesDir = layout.projectDirectory.dir("patches")

val vanillaServerJar = vanillaDir.file("server.jar")
val vanillaClassesJar = vanillaDir.file("server-classes.jar")
val widenedServerJar = vanillaDir.file("server-widened.jar")
val versionMetadataFile = metadataDir.file("version.json")
val libraryCoordinatesFile = metadataDir.file("libraries.txt")
val patchTargetsFile = buildStateDir.file("patch-targets.txt")
val runtimeMarkerFile = workspaceDir.file(".runtime-marker")
/**
 * Where the generated bytecode patch set lands inside the launcher jar.
 *
 * <p>One patch set per Minecraft version, named after the version, so a jar can
 * carry every version it was ever built for and `java -jar veltismc.jar
 * --version 26.4` either finds its patch set or says precisely which one it
 * looked for.
 */
val generatedPatchFile = layout.buildDirectory
    .file("generated-resources/META-INF/veltis/patches/$minecraftVersion.zip")
val packagedVersionFile = layout.buildDirectory
    .file("generated-resources/META-INF/veltis/minecraft-version.txt")

/**
 * How many files of one category the patch set addresses, read from the manifest
 * the patcher writes. Used only in a build log line.
 */
fun patchTargetCount(category: String): Int {
    val manifest = patchTargetsFile.asFile
    if (!manifest.isFile) return 0
    return manifest.readLines().count { it.startsWith("$category\t") }
}

val pipelineClasspath by configurations.creating {
    isCanBeConsumed = false
    isCanBeResolved = true
}

allprojects {
    group = rootProject.group
    version = rootProject.version
}

subprojects {
    apply(plugin = "java")
    apply(plugin = "java-library")
    apply(plugin = "idea")

    java.toolchain.languageVersion.set(JavaLanguageVersion.of(26))

    tasks.withType<JavaCompile> {
        options.encoding = "UTF-8"
        options.release.set(26)
    }

    idea {
        module {
            // The workspace is deliberately NOT excluded here. It holds the
            // directory the `minecraft` source set points at, and excluding a
            // source root is exactly how this ended up needing a manual "Mark
            // Directory as Sources Root" in every checkout. Excluding the
            // directory a source set declares makes the IDE disagree with Gradle
            // about what is source, and the IDE is the one that loses.
            //
            // What is excluded are the parts of a submodule's build output that
            // are inputs or byproducts rather than code: the verified jars, the
            // pristine decompile that patching copies, and the library tree.
            // None of them should be indexed, and indexing them is what made an
            // IDE import take minutes. `patched/` and `classes/` are left alone
            // because those are the files a contributor actually opens.
            excludeDirs = excludeDirs + setOf(file(".gradle"), file("build"))
        }
    }

    tasks.withType<Test> {
        useJUnitPlatform()
    }

    repositories {
        mavenCentral()
        maven("https://libraries.minecraft.net/")
        maven("https://maven.fabricmc.net/")
        maven("https://repo.spongepowered.org/repository/maven-public/")
        maven("https://jitpack.io")
    }

    dependencies {
        testImplementation(platform("org.junit:junit-bom:5.12.1"))
        testImplementation("org.junit.jupiter:junit-jupiter")
        testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    }
}

repositories {
    mavenCentral()
    maven("https://libraries.minecraft.net/")
    maven("https://maven.fabricmc.net/")
}

dependencies {
    pipelineClasspath(project(":patch-engine"))
}

tasks.jar {
    manifest {
        attributes(
            "Main-Class" to "org.veltismc.launcher.VeltisLauncher"
        )
    }
}

// Pipeline entrypoints execute engine code compiled for the toolchain
// release (26), so they must run on a matching JVM rather than Gradle's own.
val java26Launcher = javaToolchains.launcherFor {
    languageVersion = JavaLanguageVersion.of(26)
}
java.toolchain.languageVersion.set(JavaLanguageVersion.of(26))

// ---------------------------------------------------------------------------
// The `minecraft` source set
//
// A real Gradle source set rather than an `idea { module { sourceDirs } }`
// edit, which is what made IntelliJ require a manual "Mark Sources Root" and
// go stale the moment the version changed. The source root is declared
// unconditionally, so an IDE opened before the first pipeline run still has the
// right folder registered; it simply stays empty until the pipeline fills it.
//
// The compile task is scoped to the files the patch set actually addresses
// rather than the whole tree. Decompiling Minecraft does not produce sources
// that compile wholesale, and compiling all ~15 000 of them to discover that is
// not useful. Unpatched classes come from the widened server jar at runtime, so
// the compiled output is exactly the delta the patches introduce.
// ---------------------------------------------------------------------------
val minecraft by sourceSets.creating {
    java.setSrcDirs(listOf(patchedDir.asFile))
    resources.setSrcDirs(emptyList<File>())
    // A real classpath. The empty `files()` this replaces is the other half of
    // the IntelliJ problem: with no classpath, every reference from a patched
    // file into Minecraft, into VeltisMC's own modules, or into a library is
    // unresolvable, so autocomplete and Ctrl+Click could not work however the
    // source root was marked.
    compileClasspath = minecraftSourceSetClasspath
}

// The IDE half of that same declaration.
//
// A contributor who imports this directory as a Gradle project gets the source
// root from the model above and needs to do nothing. `gradlew idea` is the
// other way in, and it writes .iml files directly: Gradle's Idea plugin fills
// those from the main and test source sets only, so without this the root
// module it emits would carry no source roots at all and the legacy import
// would be blind to MinecraftServer, Level, Entity and Commands. The folder is
// read back out of the source set rather than written here, so there is still
// one declaration of where the patched tree lives and the version in it cannot
// go stale.
//
// The blanket `build` exclusion IDEA gives every root project is opened up the
// same way: un-exclude `build` as a whole, then re-exclude its children one at
// a time with the workspace left off the list. Excluding a folder that contains
// a source root is a conflict the IDE settles by dropping the root, and the
// symptom is the manual "Mark Directory as Sources Root" this build exists to
// make unnecessary — worse, everything else about the import looks healthy
// while Ctrl+Click silently does nothing.
idea {
    module {
        val rootBuild = layout.projectDirectory.dir("build").asFile
        val workspace = layout.projectDirectory.dir("build/minecraft").asFile
        val generated = (rootBuild.listFiles()?.toList() ?: emptyList())
            .filter { it != workspace }
        excludeDirs = ((excludeDirs - rootBuild) + generated + file(".gradle")).toMutableSet()
        sourceDirs = sourceDirs + minecraft.allSource.sourceDirectories.files
    }
}

/**
 * The files the patcher recorded as addressed, read from the manifest it wrote.
 *
 * <p>Deriving this from a file the engine produces — instead of re-parsing patch
 * text inside a Gradle script — keeps a single implementation of "which files
 * are patched". The file is written before patching starts, so it exists even if
 * a run fails.
 */
fun patchTargets(category: String): FileCollection = files(provider {
    val manifest = patchTargetsFile.asFile
    if (!manifest.isFile) {
        return@provider emptyList<File>()
    }
    val prefix = "$category\t"
    // Distinct(): two patches on one file list it twice, and handing javac the
    // same compilation unit twice is an error, not a no-op.
    manifest.readLines()
        .filter { it.startsWith(prefix) }
        .map { it.removePrefix(prefix) }
        .distinct()
        .map { patchedDir.asFile.resolve(it.replace('/', File.separatorChar)) }
        .filter { it.isFile }
})

/**
 * The classpath :server compiles against.
 *
 * <p>Order is significant and intentional: the compiled patched classes come
 * first so they shadow the same classes in the vanilla jar, which is what makes
 * the server run VeltisMC's implementation rather than vanilla's. It is the same
 * order `VeltisRuntime.classpath` builds for the live server, so a class that
 * resolves here resolves there too.
 *
 * <p>The baseline is deliberately the <em>unwidened</em> classes jar. The
 * development pipeline widens roughly seven thousand vanilla classes so its own
 * decompiled sources can be recompiled over them, and shipping that widened jar
 * is exactly what the bytecode patch set exists to avoid. Compiling :server
 * against it would let javac accept a reference the unwidened runtime cannot
 * resolve, and the failure would then surface on an operator's machine as an
 * IllegalAccessError instead of as a build error here. The compiler is the
 * cheapest guard available: it is already running, it reports the file and the
 * line, and it cannot be bypassed by a configuration mistake. The widened jar
 * stays on {@code minecraftSourceSetClasspath}, where the decompiled sources
 * need it and where nothing outside the pipeline looks at it.
 *
 * <p>Produced by {@code prepareVeltisRuntime}, which is why :server depends on
 * that task rather than on the individual pipeline steps: the runtime is the
 * artifact, and the per-stage tasks are how a developer produces it, not a
 * separate contract this build has to re-derive.
 */
val minecraftCompileClasspath: FileCollection = files(
    classesDir,
    vanillaClassesJar,
    fileTree(librariesDir) { include("**/*.jar") },
)

/**
 * What the `minecraft` source set resolves against.
 *
 * <p>Minecraft's own classes, plus the VeltisMC modules the patched sources call.
 * The empty classpath this replaces was the other half of the IntelliJ problem:
 * with no classpath at all, every reference from a patched file into Minecraft or
 * into VeltisMC's own code was unresolvable, so autocomplete and Ctrl+Click could
 * not work however the source root had been marked.
 *
 * <p>Deliberately excludes {@code classesDir}. A compilation unit must not resolve
 * against its own previous output, and including it would also make this task
 * depend on a directory the engine owns. The widened jar supplies every Minecraft
 * class, which is all javac needs.
 */
val minecraftSourceSetClasspath: FileCollection =
    files(widenedServerJar, fileTree(librariesDir) { include("**/*.jar") })

// The server module — the NMS entrypoint, the Veltis framework and the world
// engine in one jar — is the only thing outside the pipeline that compiles
// against Minecraft internals.
project(":server") {
    dependencies {
        implementation(files(rootProject.files(minecraftCompileClasspath)))
    }
    tasks.named("compileJava") {
        // The runtime must exist before javac runs: the patched classes it
        // compiles against are its output.
        dependsOn(":prepareVeltisRuntime")
    }
}

/**
 * Compiles the patched Minecraft sources.
 *
 * <p>Kept alongside `prepareVeltisRuntime`, which compiles the same files through
 * `javax.tools`. This task exists for the IDE and for a developer who wants to
 * step through patched code with a debugger attached to a Gradle-compiled class
 * file; the production path is the engine's in-process compiler, so there is
 * exactly one compile on `buildVeltisMC`.
 *
 * <p>Output goes to this source set's own directory rather than to the runtime's
 * {@code classes/}. The engine owns that one; two tasks writing it would be
 * either an ordering hazard or a Gradle validation failure, and the only thing
 * gained by sharing it is a second copy of the same class files.
 *
 * <p>Only the patched .java files reach javac. Decompiling Minecraft does not
 * produce sources that compile wholesale — 111 of them still contain Vineflower's
 * `<unrepresentable>` placeholder — and compiling all ~15 000 to discover that
 * buries the real errors in noise. Unpatched classes come from the widened jar,
 * so this task's output is exactly the delta the patches introduce.
 */
tasks.named<JavaCompile>("compileMinecraftJava") {
    description = "Compiles the patched Minecraft sources (IDE path)"
    group = "minecraft"
    setSource(patchTargets("code"))
    classpath = minecraftSourceSetClasspath
    options.release.set(26)
    options.encoding = "UTF-8"
    dependsOn(":applyVeltisPatches", ":widenServerJarAccess", ":downloadLibraries")
}

// The patched sources are VeltisMC's code as much as Mojang's — patch 016 calls
// VeltisBootstrap from inside DedicatedServer. A project dependency rather than a
// loose class directory, because that is what gives an IDE source-level
// navigation: Ctrl+Click on VeltisBootstrap opens VeltisBootstrap.java instead of
// a decompiled view of a class file.
dependencies {
    add("minecraftCompileOnly", project(":server"))
    // A declared output of prepareVeltisRuntime: the engine compiles the same
    // sources this source set does, and the IDE must not see a half-built one.
    tasks.named("compileMinecraftJava") {
        dependsOn(":prepareVeltisRuntime")
    }
}

// Data and module patches address resources, not code. Only the delta is copied:
// the vanilla jar already carries Minecraft's own resources, and copying them
// again would be a second set of identical bytes that could win over a patched
// one purely on classpath order. `VeltisRuntime.copyResourceDelta` does the same
// thing at runtime, so the two produce the same tree.
val processMinecraftResources = tasks.named<ProcessResources>("processMinecraftResources") {
    group = "minecraft"
    description = "Copies the resources the data and module patches changed"
    from(patchTargets("data"))
    from(patchTargets("modules"))
    destinationDir = resourcesDir.asFile
    dependsOn(":applyVeltisPatches")
}

// ---------------------------------------------------------------------------
// Generated resources packaged into the launcher jar
//
// Two small generated files, both derived from settings that already exist, and
// both generated by the engine rather than by string formatting in a build
// script. They are what lets a single jar be both the launcher and the patch
// distribution.
// ---------------------------------------------------------------------------

/**
 * Records the Minecraft version this jar was built for.
 *
 * <p>So `java -jar veltismc.jar` with no flags has a version to build against,
 * without a constant in launcher source that could drift from the build. A
 * version bump stays a one-line `gradle.properties` change.
 */
val writePackagedVersion by tasks.registering {
    group = "minecraft"
    description = "Records the Minecraft version the launcher jar defaults to"
    val target = packagedVersionFile
    inputs.property("minecraftVersion", minecraftVersion)
    outputs.file(target).withPropertyName("packagedVersion")
    doLast {
        val file = target.get().asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            # Generated by the VeltisMC build. The version java -jar veltismc.jar
            # builds for when --version is not given.
            $minecraftVersion
            """.trimIndent() + "\n"
        )
    }
}

// ---------------------------------------------------------------------------
// Pipeline steps
//
// Every step is a JavaExec with declared inputs and outputs, so Gradle can skip
// work that is genuinely done and rerun work that is not. The steps themselves
// are thin wrappers around patch-engine (see patch-engine/PipelineRunner).
// ---------------------------------------------------------------------------
fun pipelineStep(
    name: String,
    step: String,
    description: String,
) = tasks.register<JavaExec>(name) {
    this.group = "minecraft"
    this.description = description
    classpath = pipelineClasspath
    mainClass = "org.veltismc.patchengine.PipelineRunner"
    javaLauncher.set(java26Launcher)
    // patchWorkers is passed only to the step that uses it; the others ignore it.
    args(step, minecraftVersion, rootDir.absolutePath, patchWorkers.toString())
    dependsOn(":patch-engine:classes")
    // Any change to the pipeline code itself must invalidate the pipeline's
    // own outputs, otherwise a fix to the patcher would not take effect until
    // something unrelated changed.
    inputs.files(pipelineClasspath).withPropertyName("pipelineClasspath")
    // `-PveltisPipelineDebug` adds the Java stack trace to a failure. The
    // engine's own messages are written to be readable on their own, but a
    // message that comes from deep inside the JDK or a decompiler is not, and
    // without a stack there is nowhere to look.
    if (providers.gradleProperty("veltisPipelineDebug").isPresent) {
        systemProperty("veltismc.debug", "true")
    }
}

val downloadMinecraft = pipelineStep(
    "downloadMinecraft", "downloadMinecraft",
    "Resolves Minecraft $minecraftVersion on Mojang and verifies every artifact's SHA-1"
).also {
    it.configure {
        inputs.property("minecraftVersion", minecraftVersion)
        // Declaring the manifest URL as an input is what makes a change to the
        // acquisition endpoint re-run the download.
        // The classes jar alongside the bundler jar: it is extracted from the
        // bundler rather than downloaded separately, and it is the baseline the
        // bytecode patch set is cut from, so a build that does not know about it
        // would treat a required input as a stray file.
        outputs.files(versionMetadataFile, libraryCoordinatesFile, vanillaServerJar,
            vanillaClassesJar)
            .withPropertyName("minecraftArtifacts")
    }
}

val downloadLibraries = pipelineStep(
    "downloadLibraries", "downloadLibraries",
    "Fetches the library jars Mojang declares for $minecraftVersion"
).also {
    it.configure {
        inputs.files(versionMetadataFile, libraryCoordinatesFile)
            .withPropertyName("declarationInputs")
        inputs.property("minecraftVersion", minecraftVersion)
        outputs.dir(librariesDir).withPropertyName("minecraftLibraries")
        // Never skipped. Gradle decides a directory output is unchanged by
        // comparing it with its recorded snapshot, and an earlier step recreates
        // libraries/ as an empty directory before this check runs -- so on a fresh
        // clone Gradle saw an empty tree, called it up to date, and the build
        // carried on with no libraries at all. There is no honest predicate
        // available here either: metadata/libraries.txt lists the 56 resolvable
        // module coordinates, not the 114 artifact files actually fetched, so a
        // directory count cannot prove the tree is complete.
        //
        // The step is idempotent and cheap when warm: it SHA-1 verifies each
        // cached jar and fetches nothing, which measures ~370ms. Paying that to
        // remove a way to silently ship an empty classpath is the right trade.
        outputs.upToDateWhen { false }
        dependsOn(downloadMinecraft)
    }
}

/**
 * Widens class, field and method access in the verified class jar.
 *
 * <p>This runs before the decompile, not after it, and that ordering is the
 * whole point: the decompiled source is compiled against the widened jar, so a
 * method Mojang declared `protected` is `public` in both. Decompiling the
 * un-widened jar instead produces sources that cannot be compiled over the
 * widened classes at all — "attempting to assign weaker access privileges" on
 * every override the patch set touches.
 */
val widenServerJarAccess = pipelineStep(
    "widenServerJarAccess", "widenServerJarAccess",
    "Widens class/field/method access in the verified server jar"
).also {
    it.configure {
        // Before the decompile, not after it, and that ordering is the whole
        // point: the decompiled source is compiled against the widened jar, so a
        // method Mojang declared `protected` is `public` in both. Decompiling the
        // un-widened jar instead produces sources that cannot be compiled over the
        // widened classes at all — "attempting to assign weaker access privileges"
        // on every override the patch set touches.
        inputs.file(vanillaClassesJar).withPropertyName("serverClassesJar")
        outputs.file(widenedServerJar).withPropertyName("widenedServerJar")
        dependsOn(downloadMinecraft)
    }
}

val decompileMinecraft = pipelineStep(
    "decompileMinecraft", "decompileMinecraft",
    "Decompiles the verified server jar into the workspace's pristine source tree"
).also {
    it.configure {
        inputs.files(widenedServerJar, libraryCoordinatesFile)
            .withPropertyName("decompileInputs")
        outputs.dir(sourceDir).withPropertyName("decompiledSource")
        dependsOn(downloadLibraries, widenServerJarAccess)
    }
}

val applyVeltisPatches = pipelineStep(
    "applyVeltisPatches", "applyVeltisPatches",
    "Mirrors the decompiled source and applies patches/{code,data,modules}"
).also {
    it.configure {
        inputs.dir(patchesDir).withPropertyName("patchSet")
        inputs.dir(sourceDir).withPropertyName("decompiledSource")
        inputs.property("minecraftVersion", minecraftVersion)
        inputs.property("patchWorkers", patchWorkers)
        outputs.dir(patchedDir).withPropertyName("patchedSource")
        outputs.file(patchTargetsFile).withPropertyName("patchTargets")
        dependsOn(decompileMinecraft)
    }
}

val rebuildVeltisPatches = pipelineStep(
    "rebuildVeltisPatches", "rebuildVeltisPatches",
    "Regenerates patches/ from the current contents of the patched workspace"
).also {
    it.configure {
        // Deliberately NOT dependsOn(applyVeltisPatches). The rebuild workflow is
        // "edit a file in patched/ in the IDE, then run this task", and apply
        // re-mirrors the pristine source over patched/ with REPLACE_EXISTING --
        // so depending on it would discard the very edits being captured, and the
        // rebuild would diff a tree it had just overwritten. Only the pristine
        // baseline is needed here, which is decompileMinecraft's output.
        dependsOn(decompileMinecraft)

        // patched/ is hand-edited between runs, so its contents cannot be tracked
        // as an input: Gradle would either miss a change or consider the task up to
        // date while patches/ is stale. Reading the tree live and always running is
        // the only honest description of what this task does.
        outputs.upToDateWhen { false }
        outputs.dir(patchesDir).withPropertyName("regeneratedPatches")

        // -PpatchName="Improve Entity Logging" names the one patch this rebuild
        // creates instead of the name derived from the target path. A system
        // property rather than a fifth argument so the pipeline's step signature
        // stays (step, version, root, workers) for every other task, and the
        // rebuilder is the one place that decides what a name means.
        providers.gradleProperty("patchName").orNull?.let { requested ->
            systemProperty("veltismc.patchName", requested)
        }
    }
}

val cleanVeltisPatches = pipelineStep(
    "cleanVeltisPatches", "cleanVeltisPatches",
    "Discards the patched workspace and its compiled output"
).also {
    it.configure {
        // A clean task is meaningless if it can be up to date.
        outputs.upToDateWhen { false }
        outputs.dir(patchedDir).withPropertyName("patchedSource")
        outputs.dir(classesDir).withPropertyName("minecraftClasses")
        outputs.dir(resourcesDir).withPropertyName("minecraftResources")
    }
}

/**
 * The two commands a contributor actually types, as aliases of the pipeline's
 * own names.
 *
 * <p>Both spellings run the same task, so nothing is duplicated and nothing can
 * drift: `applyPatches` is `applyVeltisPatches`, and `rebuildPatches` is
 * `rebuildVeltisPatches`. The shorter pair is what CONTRIBUTING.md documents
 * because it is what reads like an instruction; the longer pair stays because
 * CI, the README and the engine's own log lines already use it, and renaming
 * them would break both for no gain.
 */
tasks.register("applyPatches") {
    group = "minecraft"
    description = "Mirrors the pristine decompiled source and applies patches/{code,data,modules}"
    dependsOn(applyVeltisPatches)
}

tasks.register("rebuildPatches") {
    group = "minecraft"
    description = "Turns edited files under patched/ back into patches/, renumbered contiguously"
    dependsOn(rebuildVeltisPatches)
}

/**
 * The whole chain, in one call, through the code the launcher runs.
 *
 * <p>This is the build's answer to "make the runtime ready", and it is the same
 * `VeltisRuntime.prepare()` a cold `java -jar veltismc.jar` calls. One
 * implementation, two callers — which is the point. A separate Gradle
 * composition of download/decompile/patch/compile tasks could drift from what a
 * server actually does, and the drift would show up as a jar that builds fine
 * and starts vanilla. The fine-grained tasks below still exist and still run:
 * they are what an IDE and a developer use to walk one stage at a time.
 *
 * <p>The engine keeps its own per-stage validity rules, so this task is skipped
 * only when the marker it writes still matches the version, the artifact hash,
 * the patch revision and the compiler release.
 */
val prepareVeltisRuntime = pipelineStep(
    "prepareVeltisRuntime", "prepareVeltisRuntime",
    "Builds the patched runtime exactly as the launcher does, and records its identity"
).also {
    it.configure {
        inputs.dir(patchesDir).withPropertyName("patchSet")
        inputs.property("minecraftVersion", minecraftVersion)
        inputs.property("patchWorkers", patchWorkers)
        inputs.property("classFileRelease", 26)
        // The whole workspace is this task's output, because this task can build
        // all of it: it resolves, downloads, verifies, widens, decompiles, patches
        // and compiles for itself, each stage behind its own cache. Declaring only
        // classes/ would leave the download and decompile stages looking like
        // outputs of the per-stage tasks, whose ordering this task does not and
        // should not depend on.
        outputs.dir(vanillaDir).withPropertyName("vanillaArtifacts")
        outputs.dir(metadataDir).withPropertyName("minecraftMetadata")
        outputs.dir(librariesDir).withPropertyName("minecraftLibraries")
        outputs.dir(sourceDir).withPropertyName("decompiledSource")
        outputs.dir(patchedDir).withPropertyName("patchedSource")
        outputs.dir(classesDir).withPropertyName("patchedClasses")
        outputs.dir(resourcesDir).withPropertyName("patchedResources")
        outputs.dir(buildStateDir).withPropertyName("pipelineState")
        outputs.file(runtimeMarkerFile).withPropertyName("runtimeIdentity")

        // The per-stage tasks and this one both produce the workspace, which Gradle
        // will call an overlapping output and refuse to cache. It is a real
        // duplication, and the ordering below is what keeps it harmless: when a
        // developer asks for both in one invocation (`prepareMinecraft
        // buildVeltisMC`) the per-stage chain runs first and this task then finds
        // every stage cached, so it reduces to the compile and the identity. The
        // alternative — making this task depend on the per-stage chain — would
        // mean the launcher and the build no longer share one implementation.
        mustRunAfter(downloadMinecraft, downloadLibraries, widenServerJarAccess,
            decompileMinecraft, applyVeltisPatches, rebuildVeltisPatches)
    }
}

/**
 * Fails the build unless the runtime really loads its patched classes.
 *
 * <p>Replaces the old check that unpacked the pre-packaged server jar and
 * compared bytes. That check could only prove a class was present in an
 * archive; the
 * failure it guards against is a classpath decision — vanilla winning because an
 * entry was ordered differently, or because a library shadowed it. This one
 * builds the loader the server will use and asks it where each patched class
 * resolves from and whether the bytes are patched.
 *
 * <p>Three layers instead of one, because each catches a different mistake:
 * the compiled class exists, it differs from vanilla (so no patch silently
 * applied nothing), and the loader serves exactly those bytes.
 */
val verifyVeltisRuntime = pipelineStep(
    "verifyVeltisRuntime", "verifyVeltisRuntime",
    "Proves the runtime classpath loads the patched classes and not the vanilla ones"
).also {
    it.configure {
        // The classpath input is declared by pipelineStep; only the dependency on
        // what it verifies is this task's own.
        dependsOn(prepareVeltisRuntime)
        // `-PveltisGuardCanary` reverses the classpath on purpose so the guard's
        // failure can be demonstrated rather than asserted. Forwarded explicitly
        // because a Gradle property is not a system property: without this the run
        // reports success and proves nothing, which is the one outcome a canary
        // must never produce.
        if (providers.gradleProperty("veltisGuardCanary").isPresent) {
            systemProperty("veltisGuardCanary", "true")
        }
    }
}

/**
 * Publishes the bytecode patch set into the resources the launcher jar is built
 * from.
 *
 * <p>This is the one thing that makes `java -jar server.jar` a complete
 * distribution: the patch set that turns a downloaded vanilla jar into a
 * VeltisMC server travels inside the launcher, under a name that says which
 * Minecraft version it addresses. An operator never has a `patches/` directory,
 * a Git checkout, a decompiler or a compiler, and never needs one.
 *
 * <p>Generated rather than assembled by the packaging script, so the file that
 * ships is the file the applier reads back and re-validates — a patch set that
 * this build could not read would fail here instead of on a stranger's machine.
 */
val publishBytecodePatch by tasks.registering {
    group = "minecraft"
    description = "Publishes the bytecode patch set the launcher jar distributes"
    val source = workspaceDir.file("build/veltis-patch.zip")
    inputs.file(source).withPropertyName("bytecodePatchSet")
    inputs.property("minecraftVersion", minecraftVersion)
    outputs.file(generatedPatchFile).withPropertyName("publishedPatchSet")
    dependsOn(prepareVeltisRuntime)
    doLast {
        val target = generatedPatchFile.get().asFile
        val version = "$minecraftVersion"
        target.parentFile.mkdirs()
        Files.copy(
            source.asFile.toPath(),
            target.toPath(),
            StandardCopyOption.REPLACE_EXISTING,
        )
        logger.lifecycle(
            "[Veltis] Published {} ({} bytes) as META-INF/veltis/patches/{}.zip",
            source.asFile,
            target.length(),
            version,
        )
    }
}

/**
 * The per-stage chain, for an IDE and for a developer working on patches.
 *
 * <p>Not on the production path: `prepareVeltisRuntime` above builds the same
 * result through the engine's own staging, and `compileMinecraftJava` exists so
 * IntelliJ can resolve, navigate and debug the patched sources with a real
 * Gradle compile classpath rather than a folder someone marked by hand.
 */
val prepareMinecraft by tasks.registering {
    group = "minecraft"
    description = "Downloads, decompiles, patches and compiles Minecraft $minecraftVersion (IDE path)"
    dependsOn(applyVeltisPatches, ":compileMinecraftJava", processMinecraftResources)
}

// ---------------------------------------------------------------------------
// Packaging
// ---------------------------------------------------------------------------

/**
 * The distributable: the launcher, with no Minecraft code inside it.
 *
 * <p>One jar, and it is not a build prerequisite for running it. `java -jar
 * veltismc.jar` builds the runtime on first launch and reuses it afterwards, so
 * the same artifact serves a developer, a CI job that wants the work done up
 * front, and an operator who has never seen a Gradle build. `buildVeltisMC` still
 * exists to do that work ahead of time — it is a prebuilder and a release step,
 * not a gate on starting a server.
 */
val packageVeltisMC by tasks.registering(Copy::class) {
    group = "minecraft"
    description = "Packages the EULA-compliant launcher jar (no Minecraft code)"
    from(project(":launcher").tasks.named("uberJar"))
    into(layout.buildDirectory.dir("distributions"))
    rename { "veltismc.jar" }
    dependsOn(":launcher:uberJar")
}

val buildVeltisMC = tasks.register("buildVeltisMC") {
    group = "minecraft"
    description = "Builds the runtime and the launcher jar (optional; the jar self-bootstraps)"
    dependsOn(prepareVeltisRuntime, verifyVeltisRuntime, packageVeltisMC,
        ":launcher:verifyDistributableContent")
    doLast {
        logger.lifecycle("VeltisMC build completed:")
        logger.lifecycle("  launcher: {}", layout.buildDirectory.file("distributions/veltismc.jar").get().asFile)
        logger.lifecycle("  runtime:  {} ({} patched classes)", classesDir.asFile, patchTargetCount("code"))
    }
}

/**
 * The standard `build` produces the distributable jar and verifies the runtime,
 * so a green `build` means a jar that will actually start patched.
 *
 * <p>It does run the runtime preparation, and it has to: `:server` compiles
 * against Minecraft's classes, and the guard has to have a real artifact in order
 * to say anything about one. On a machine that already has the workspace that is
 * a warm validation — a few hundred milliseconds of reading a jar and hashing a
 * file — and on a fresh clone it is the one time the full chain runs, so the
 * first `./gradlew build` costs a download and a decompile and every later one
 * does not. `./gradlew buildVeltisMC` exists for the case where that work is the
 * point rather than a side effect.
 */
tasks.named("build") {
    dependsOn(verifyVeltisRuntime, packageVeltisMC, ":launcher:verifyDistributableContent")
}
