import org.gradle.jvm.toolchain.JavaLanguageVersion
import java.nio.file.Files
import java.nio.file.StandardCopyOption

plugins {
    java
    idea
}

val asmVersion = "9.10.1"

subprojects {
    configurations.all {
        resolutionStrategy {
            force(
                "org.ow2.asm:asm:$asmVersion",
                "org.ow2.asm:asm-commons:$asmVersion",
                "org.ow2.asm:asm-tree:$asmVersion",
                "org.ow2.asm:asm-analysis:$asmVersion",
                "org.ow2.asm:asm-util:$asmVersion"
            )
        }
    }
}

group = "org.veltismc"
version = "1.0.0-SNAPSHOT"

// ---------------------------------------------------------------------------
// Minecraft pipeline configuration
//
// The development cache lives at minecraft/<minecraftVersion>/, laid out by
// patch-engine's VeltisWorkspace: the pristine decompile gets its own tree at
// minecraft/<version>/ — the only directory the decompile step writes, and the
// one a contributor reads as minecraft/<version>/net/minecraft/... — and
// everything else the pipeline produces sits in the workspace beside it at
// minecraft/workspace/<version>/. There are no temporary or per-run
// directories anywhere: every step reads and writes fixed, named locations,
// and the whole tree is git-ignored and outside `build/`, so neither
// `./gradlew clean` nor an IDE's blanket build/ exclusion can hide the
// workspace from the toolchain that reads it.
//
// A server installation uses a different layout (Vanilla/<v> and Veltis/<v>
// beside the server, with its work tree in the system temporary directory);
// this is the contributor's one.
// ---------------------------------------------------------------------------
val minecraftVersion = providers.gradleProperty("minecraftVersion")
    .orElse("26.3").get()

/**
 * How many targets the patcher applies in parallel. One target is one task, so
 * a patch set with fewer targets than workers simply uses fewer threads. Bounded
 * on purpose: the pool is sized from this, never from the machine, so a build
 * behaves the same on a laptop and on CI.
 */
val patchWorkers = providers.gradleProperty("patchWorkers")
    .map { it.toInt() }
    .orElse(maxOf(1, Runtime.getRuntime().availableProcessors() - 1))
    .get()

val workspaceDir = layout.projectDirectory.dir("minecraft/workspace/$minecraftVersion")
val vanillaDir = workspaceDir.dir("vanilla")
val metadataDir = workspaceDir.dir("metadata")
val librariesDir = workspaceDir.dir("libraries")
// Beside the workspace, not inside it: the pristine decompile is the tree only
// the decompile step writes, and separating it keeps Gradle's snapshot of it
// meaningful (a rebuild under classes/ must not look like a change to the
// baseline every patch applies to). It is also the path a contributor reads —
// minecraft/<version>/net/minecraft/... — and the source root the IDE attaches
// to the Minecraft library.
val sourceDir = layout.projectDirectory.dir("minecraft/$minecraftVersion")
val patchedDir = workspaceDir.dir("patched")
val classesDir = workspaceDir.dir("classes")
val resourcesDir = workspaceDir.dir("resources")
val buildStateDir = workspaceDir.dir("build")
// The exploded mirror of the patch set's payload directory: the same deltas and
// resources the container carries, as plain files under the names the index
// uses. A generated view of one run's output, declared as an output of the task
// that writes it so a clean build knows it exists.
val runtimePatchesDir = workspaceDir.dir("runtime-patches")
val patchesDir = layout.projectDirectory.dir("server/Shulker")

val vanillaServerJar = vanillaDir.file("server.jar")
val vanillaClassesJar = vanillaDir.file("server-classes.jar")
val widenedServerJar = vanillaDir.file("server-widened.jar")
/**
 * The patched runtime artifact, at the path {@code VeltisWorkspace}'s
 * development layout gives it. Vanilla plus the Veltis bytecode patches, one
 * complete class set: the same jar `VeltisRuntime.classpath` puts first on the
 * live server's classpath, and the same one this build hands javac and the IDE,
 * so there is never a question of which copy of a class wins.
 */
val veltisServerJar = workspaceDir.file("veltis-server.jar")
val versionMetadataFile = metadataDir.file("version.json")
val libraryCoordinatesFile = metadataDir.file("libraries.txt")
val patchTargetsFile = buildStateDir.file("patch-targets.txt")
val runtimeMarkerFile = workspaceDir.file(".runtime-marker")
/**
 * Where the generated bytecode patch set lands inside the launcher jar.
 *
 * <p>One patch set per Minecraft version, named after the version, so a jar can
 * carry every version it was ever built for and `java -jar veltismc.jar
 * --version 26.4` either finds its patch set or says precisely which one it
 * looked for.
 */
val generatedPatchFile = layout.buildDirectory
    .file("generated-resources/META-INF/veltis/patches/$minecraftVersion.zip")
val packagedVersionFile = layout.buildDirectory
    .file("generated-resources/META-INF/veltis/minecraft-version.txt")
val packagedJavaVersionFile = layout.buildDirectory
    .file("generated-resources/META-INF/veltis/java-version.txt")

// ---------------------------------------------------------------------------
// Java compatibility
//
// Two separate numbers, and keeping them apart is the whole change:
//
//   * the *toolchain* is the JDK the build compiles with, kept at 26 so a
//     contributor's existing setup keeps working;
//   * the *class-file release* is the bytecode every module and every patched
//     Minecraft class is written as, and it is the minimum JVM the packaged
//     server will load on.
//
// Minecraft 26.3's own classes are class-file version 69 (Java 25) and its
// version document declares `javaVersion.majorVersion = 25`, so 25 is the floor
// the rest of the system must match. `javac --release 25` on a JDK 26 produces
// exactly that, which is what lets one build serve both Java 25 and Java 26.
//
// The value is read from the resolved metadata when it is available and falls
// back to 25 for a fresh checkout; `-PveltisJavaRelease=` overrides it for
// experiments and `-PveltisToolchainVersion=` moves the build JDK.
// ---------------------------------------------------------------------------
fun minecraftMetadataJavaRelease(): Int {
    val file = metadataDir.file("version.json").asFile
    if (!file.isFile) return 25
    return try {
        val match = Regex("\"javaVersion\"\\s*:\\s*\\{[^}]*\"majorVersion\"\\s*:\\s*(\\d+)")
            .find(file.readText(Charsets.UTF_8))
        match?.groupValues?.get(1)?.toIntOrNull() ?: 25
    } catch (e: Exception) {
        25
    }
}

val veltisJavaRelease: Int = providers.gradleProperty("veltisJavaRelease")
    .map { it.toInt() }
    .orElse(minecraftMetadataJavaRelease())
    .get()

val veltisToolchain: Int = providers.gradleProperty("veltisToolchainVersion")
    .map { it.toInt() }
    .orElse(26)
    .get()

/**
 * How many files of one category the patch set addresses, read from the manifest
 * the patcher writes. Used only in a build log line.
 */
fun patchTargetCount(category: String): Int {
    val manifest = patchTargetsFile.asFile
    if (!manifest.isFile) return 0
    return manifest.readLines().count { it.startsWith("$category\t") }
}

val pipelineClasspath by configurations.creating {
    isCanBeConsumed = false
    isCanBeResolved = true
}

allprojects {
    group = rootProject.group
    version = rootProject.version
}

subprojects {
    apply(plugin = "java")
    apply(plugin = "java-library")
    apply(plugin = "idea")

    java.toolchain.languageVersion.set(JavaLanguageVersion.of(veltisToolchain))

    tasks.withType<JavaCompile> {
        options.encoding = "UTF-8"
        options.release.set(veltisJavaRelease)
    }

    idea {
        module {
            // The workspace is deliberately NOT excluded here. It holds the
            // directory the `minecraft` source set points at, and excluding a
            // source root is exactly how this ended up needing a manual "Mark
            // Directory as Sources Root" in every checkout. Excluding the
            // directory a source set declares makes the IDE disagree with Gradle
            // about what is source, and the IDE is the one that loses.
            //
            // What is excluded are the parts of a submodule's build output that
            // are inputs or byproducts rather than code: the verified jars, the
            // pristine decompile that patching copies, and the library tree.
            // None of them should be indexed, and indexing them is what made an
            // IDE import take minutes. `patched/` and `classes/` are left alone
            // because those are the files a contributor actually opens.
            excludeDirs = excludeDirs + setOf(file(".gradle"), file("build"))
        }
    }

    tasks.withType<Test> {
        useJUnitPlatform()
    }

    repositories {
        mavenCentral()
        maven("https://libraries.minecraft.net/")
        maven("https://maven.fabricmc.net/")
        maven("https://repo.spongepowered.org/repository/maven-public/")
        maven("https://jitpack.io")
    }

    dependencies {
        testImplementation(platform("org.junit:junit-bom:5.12.1"))
        testImplementation("org.junit.jupiter:junit-jupiter")
        testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    }
}

repositories {
    mavenCentral()
    maven("https://libraries.minecraft.net/")
    maven("https://maven.fabricmc.net/")
}

dependencies {
    pipelineClasspath(project(":patch-engine"))
    // The decompiler the pipeline runs to produce `source/`. Named here rather
    // than exported by `:patch-engine`: that module declares Vineflower
    // `compileOnly`, so it cannot reach a runtime classpath, an installed jar or
    // `libraries/` — and this is the one classpath that actually needs it.
    // Removing it here breaks `decompileMinecraft` (and therefore `applyPatches`)
    // with a `NoClassDefFoundError` on first use of the marker's options.
    pipelineClasspath("org.vineflower:vineflower:1.12.0")
}

tasks.jar {
    manifest {
        attributes(
            "Main-Class" to "org.veltismc.launcher.VeltisLauncher"
        )
    }
}

// Pipeline entrypoints execute engine code compiled for the toolchain release,
// so they must run on a matching JVM rather than Gradle's own. The toolchain and
// the bytecode release are independent: this JVM compiles `--release
// $veltisJavaRelease` output for the server while itself running on JDK
// $veltisToolchain.
val pipelineLauncher = javaToolchains.launcherFor {
    languageVersion = JavaLanguageVersion.of(veltisToolchain)
}
java.toolchain.languageVersion.set(JavaLanguageVersion.of(veltisToolchain))

// ---------------------------------------------------------------------------
// The `minecraft` source set
//
// A real Gradle source set rather than an `idea { module { sourceDirs } }`
// edit, which is what made IntelliJ require a manual "Mark Sources Root" and
// go stale the moment the version changed. The source root is declared
// unconditionally, so an IDE opened before the first pipeline run still has the
// right folder registered; it simply stays empty until the pipeline fills it.
//
// The compile task is scoped to the files the patch set actually addresses
// rather than the whole tree. Decompiling Minecraft does not produce sources
// that compile wholesale, and compiling all ~15 000 of them to discover that is
// not useful. Unpatched classes come from the widened server jar at runtime, so
// the compiled output is exactly the delta the patches introduce.
// ---------------------------------------------------------------------------
val minecraft by sourceSets.creating {
    java.setSrcDirs(listOf(patchedDir.asFile))
    resources.setSrcDirs(emptyList<File>())
    // A real classpath. The empty `files()` this replaces is the other half of
    // the IntelliJ problem: with no classpath, every reference from a patched
    // file into Minecraft, into VeltisMC's own modules, or into a library is
    // unresolvable, so autocomplete and Ctrl+Click could not work however the
    // source root was marked.
    compileClasspath = minecraftSourceSetClasspath
}

// The IDE half of that same declaration.
//
// A contributor who imports this directory as a Gradle project gets the source
// root from the model above and needs to do nothing. `gradlew idea` is the
// other way in, and it writes .iml files directly: Gradle's Idea plugin fills
// those from the main and test source sets only, so without the sourceDirs line
// below the root module it emits would carry no source roots at all and the
// legacy import would be blind to MinecraftServer, Level, Entity and Commands.
// The folder is read back out of the source set rather than written here, so
// there is still one declaration of where the patched tree lives and the
// version in it cannot go stale.
//
// Minecraft itself arrives as a library, not as project source: classes from
// the pipeline's compiled output and verified baseline, sources from the
// pristine decompile at minecraft/<version>. Gradle's Idea plugin already
// emits file dependencies as classpath libraries, but a file dependency has no
// concept of sources — so the source attachment for those that carry Minecraft
// is declared here, and Ctrl+Click opens decompiled source instead of a
// FernFlower view of a class file. The whole tree lives under minecraft/,
// outside build/, so neither the blanket build/ exclusion nor a clean can hide
// it from the IDE.
idea {
    module {
        excludeDirs = excludeDirs + setOf(file("build"), file(".gradle"))
        sourceDirs = sourceDirs + minecraft.allSource.sourceDirectories.files
        iml {
            withXml(Action<org.gradle.api.XmlProvider> {
                val module = asElement()
                val document = module.ownerDocument
                // `.iml` regeneration merges with what is already on disk, so
                // re-running `gradlew idea` must not append this library a
                // second (third, ...) time: the guard makes the whole line
                // idempotent.
                // The name is ASCII on purpose: the .iml writer normalises the
                // em-dash, and a guard that compared the un-normalised string
                // would never recognise the entry a previous run wrote.
                val libraryName = "Minecraft $minecraftVersion - Veltis Patched"
                val alreadyDeclared = document.getElementsByTagName("library")
                    .let { libs -> (0 until libs.length).any { i ->
                        (libs.item(i) as? org.w3c.dom.Element)
                            ?.getAttribute("name") == libraryName } }
                if (!alreadyDeclared) {
                    val entry = document.createElement("orderEntry")
                    entry.setAttribute("type", "module-library")
                    val library = document.createElement("library")
                    library.setAttribute("name", libraryName)
                    library.appendChild(rootsElement(document, "CLASSES", minecraftLibraryClasses()))
                    library.appendChild(document.createElement("JAVADOC"))
                    // Only the pristine decompile: patched/ is this module's own source
                    // root, and a file that is both a module source and a library source
                    // is indexed twice for no gain. Unpatched classes — the ones not in
                    // patched/ — resolve through here.
                    library.appendChild(rootsElement(document, "SOURCES",
                        listOf(sourceDir.asFile)))
                    entry.appendChild(library)
                    module.appendChild(entry)
                }
            })
        }
    }
}

/**
 * A `<CLASSES>`/`<SOURCES>` element holding one `<root>` per file, in the .iml
 * URL form (`file://…` for a directory, `jar://…!/` for an archive).
 */
fun rootsElement(document: org.w3c.dom.Document, tag: String, files: List<File>): org.w3c.dom.Element {
    val element = document.createElement(tag)
    for (file in files) {
        val root = document.createElement("root")
        val path = file.invariantSeparatorsPath
        root.setAttribute("url", if (file.isDirectory) "file://$path" else "jar://$path!/")
        element.appendChild(root)
    }
    return element
}

/**
 * Every class root Minecraft resolves from in the IDE: the patched runtime
 * artifact (vanilla plus the Veltis bytecode patches — the same jar the server
 * runs and javac compiles against) and Mojang's declared libraries — the same
 * entries `VeltisRuntime.classpath` builds for the live server, minus this
 * process's own jar.
 *
 * <p>No directory of loose class files and no separate vanilla jar: a second
 * copy of a class on the library's root list is how "which one wins" becomes a
 * question that has to be answered at all, and the artifact is complete.
 */
fun minecraftLibraryClasses(): List<File> {
    val jars = librariesDir.asFile.walkTopDown()
        .filter { it.isFile && it.extension == "jar" }
        .toList()
    return listOf(veltisServerJar.asFile) + jars
}

/**
 * The files the patcher recorded as addressed, read from the manifest it wrote.
 *
 * <p>Deriving this from a file the engine produces — instead of re-parsing patch
 * text inside a Gradle script — keeps a single implementation of "which files
 * are patched". The file is written before patching starts, so it exists even if
 * a run fails.
 */
fun patchTargets(category: String): FileCollection = files(provider {
    val manifest = patchTargetsFile.asFile
    if (!manifest.isFile) {
        return@provider emptyList<File>()
    }
    val prefix = "$category\t"
    // Distinct(): two patches on one file list it twice, and handing javac the
    // same compilation unit twice is an error, not a no-op.
    manifest.readLines()
        .filter { it.startsWith(prefix) }
        .map { it.removePrefix(prefix) }
        .distinct()
        .map { patchedDir.asFile.resolve(it.replace('/', File.separatorChar)) }
        .filter { it.isFile }
})

/**
 * The classpath :server compiles against.
 *
 * <p>Two kinds of entry, in this order: the patched runtime artifact and
 * Mojang's declared libraries. It is exactly `VeltisRuntime.classpath` for the
 * live server minus this process's own jar, so a class that resolves here
 * resolves there too — javac sees the definition the runtime loads, never a
 * baseline copy of it. The artifact is complete (vanilla with the Veltis
 * bytecode patches applied), so a patched class appears once and there is no
 * "which entry wins" question to answer.
 *
 * <p>The artifact is the <em>unwidened</em> runtime. The development pipeline
 * widens roughly seven thousand vanilla classes so its own decompiled sources
 * can be recompiled over them, and shipping that widened jar is exactly what
 * the bytecode patch set exists to avoid. Compiling :server against it would
 * let javac accept a reference the unwidened runtime cannot resolve, and the
 * failure would then surface on an operator's machine as an IllegalAccessError
 * instead of as a build error here. The compiler is the cheapest guard
 * available: it is already running, it reports the file and the line, and it
 * cannot be bypassed by a configuration mistake. The widened jar stays on
 * {@code minecraftSourceSetClasspath}, where the decompiled sources need it
 * and where nothing outside the pipeline looks at it.
 *
 * <p>Produced by {@code prepareVeltisRuntime}, which is why :server depends on
 * that task rather than on the individual pipeline steps: the runtime is the
 * artifact, and the per-stage tasks are how a developer produces it, not a
 * separate contract this build has to re-derive.
 */
val minecraftCompileClasspath: FileCollection = files(
    veltisServerJar,
    fileTree(librariesDir) { include("**/*.jar") },
)

/**
 * What the `minecraft` source set resolves against.
 *
 * <p>Minecraft's own classes, plus the VeltisMC modules the patched sources call.
 * The empty classpath this replaces was the other half of the IntelliJ problem:
 * with no classpath at all, every reference from a patched file into Minecraft or
 * into VeltisMC's own code was unresolvable, so autocomplete and Ctrl+Click could
 * not work however the source root had been marked.
 *
 * <p>Deliberately excludes {@code classesDir}. A compilation unit must not resolve
 * against its own previous output, and including it would also make this task
 * depend on a directory the engine owns. The widened jar supplies every Minecraft
 * class, which is all javac needs.
 */
val minecraftSourceSetClasspath: FileCollection =
    files(widenedServerJar, fileTree(librariesDir) { include("**/*.jar") })

// The server module — the NMS entrypoint, the Veltis framework and the world
// engine in one jar — is the only thing outside the pipeline that compiles
// against Minecraft internals.
project(":server") {
    dependencies {
        implementation(files(rootProject.files(minecraftCompileClasspath)))
    }
    idea {
        module {
            // Gradle's Idea plugin already turns the file dependencies above into
            // classpath libraries, but a file dependency has no concept of
            // sources: Ctrl+Click on ServerLevel would open a FernFlower view of
            // a class file instead of the file being edited. Attach the patched
            // tree first — it holds the classes the patch set addresses, and it
            // is where the patched definitions of everything else live too — and
            // the pristine decompile behind it. Only to the entries that
            // actually carry Minecraft's classes: the library jars are somebody
            // else's code, and pointing their sources at the decompile would
            // open the wrong file for a right click.
            iml {
                withXml(Action<org.gradle.api.XmlProvider> {
                    val module = asElement()
                    val document = module.ownerDocument
                    val entries = module.getElementsByTagName("orderEntry")
                    for (i in 0 until entries.length) {
                        val entry = entries.item(i) as? org.w3c.dom.Element ?: continue
                        if (entry.getAttribute("type") != "module-library") continue
                        val classes = entry.getElementsByTagName("CLASSES")
                        if (classes.length == 0) continue
                        val urls = mutableListOf<String>()
                        val roots = classes.item(0).childNodes
                        for (j in 0 until roots.length) {
                            val node = roots.item(j) as? org.w3c.dom.Element ?: continue
                            if (node.tagName == "root") urls += node.getAttribute("url")
                        }
                        val carriesMinecraft = urls.any { url ->
                            // The .iml URL form for a jar is `jar://…!/`, so an
                            // archive is matched by its file name, not by where
                            // it ends.
                            (url.endsWith("/classes")
                                || url.contains("/vanilla/")
                                || url.contains("/veltis-server.jar"))
                                && url.contains("/minecraft/")
                        }
                        if (!carriesMinecraft) continue
                        val sources = entry.getElementsByTagName("SOURCES")
                        if (sources.length > 0) {
                            // In the .iml an orderEntry's CLASSES/JAVADOC/SOURCES
                            // live under its inner <library>, so the replacement
                            // has to happen there, not on the orderEntry.
                            val oldSources = sources.item(0) as? org.w3c.dom.Element ?: continue
                            val library = oldSources.parentNode as? org.w3c.dom.Element
                            if (library != null) {
                                library.replaceChild(
                                    rootsElement(document, "SOURCES",
                                        listOf(patchedDir.asFile, sourceDir.asFile)),
                                    oldSources,
                                )
                            }
                        }
                    }
                })
            }
        }
    }
    tasks.named("compileJava") {
        // The runtime must exist before javac runs: the patched classes it
        // compiles against are its output.
        dependsOn(":prepareVeltisRuntime")
    }
    tasks.withType<Test>().configureEach {
        // The NMS integration tests load real Minecraft classes. Prepending the
        // dev-visible classes and the widened jar keeps them running against
        // the same patched classes javac and the IDE see, ahead of the packaged
        // artifact, and keeps every `net.minecraft.*` class unsigned: the
        // compile classpath carries the unsigned runtime artifact now, but the
        // prepend is what guarantees no test can ever pull a class from a jar
        // whose signature disagrees with another entry's. Compile classpaths
        // are deliberately untouched: :server must keep compiling against the
        // unwidened runtime so access errors stay build errors.
        classpath = files(classesDir, widenedServerJar, this.classpath)
    }
    tasks.withType<Test>().configureEach {
        // `-PveltisBench` runs the low-resource engine benchmark in the shape of
        // the deployment it exists for: one visible core (the JVM sizes its
        // container-aware pools and worker ceiling from this) and a two-gigabyte
        // heap (the pool ceilings are a fraction of it). Off by default so a
        // normal build never pays the heap or the time.
        if (providers.gradleProperty("veltisBench").isPresent) {
            maxHeapSize = "2g"
            jvmArgs("-XX:ActiveProcessorCount=1", "-Dveltis.bench=true")
            systemProperty(
                "veltis.bench.config",
                providers.gradleProperty("veltisBenchConfig").getOrElse("resource"),
            )
        }
    }
}

/**
 * Compiles the patched Minecraft sources.
 *
 * <p>Kept alongside `prepareVeltisRuntime`, which compiles the same files through
 * `javax.tools`. This task exists for the IDE and for a developer who wants to
 * step through patched code with a debugger attached to a Gradle-compiled class
 * file; the production path is the engine's in-process compiler, so there is
 * exactly one compile on `buildVeltisMC`.
 *
 * <p>Output goes to this source set's own directory rather than to the runtime's
 * {@code classes/}. The engine owns that one; two tasks writing it would be
 * either an ordering hazard or a Gradle validation failure, and the only thing
 * gained by sharing it is a second copy of the same class files.
 *
 * <p>Only the patched .java files reach javac. Decompiling Minecraft does not
 * produce sources that compile wholesale — 111 of them still contain Vineflower's
 * `<unrepresentable>` placeholder — and compiling all ~15 000 to discover that
 * buries the real errors in noise. Unpatched classes come from the widened jar,
 * so this task's output is exactly the delta the patches introduce.
 */
tasks.named<JavaCompile>("compileMinecraftJava") {
    description = "Compiles the patched Minecraft sources (IDE path)"
    group = "minecraft"
    setSource(patchTargets("code"))
    classpath = minecraftSourceSetClasspath
    options.release.set(veltisJavaRelease)
    options.encoding = "UTF-8"
    dependsOn(":applyVeltisPatches", ":widenServerJarAccess", ":downloadLibraries")
}

// The patched sources are VeltisMC's code as much as Mojang's — patch 016 calls
// VeltisBootstrap from inside DedicatedServer. A project dependency rather than a
// loose class directory, because that is what gives an IDE source-level
// navigation: Ctrl+Click on VeltisBootstrap opens VeltisBootstrap.java instead of
// a decompiled view of a class file.
dependencies {
    add("minecraftCompileOnly", project(":server"))
    // A declared output of prepareVeltisRuntime: the engine compiles the same
    // sources this source set does, and the IDE must not see a half-built one.
    tasks.named("compileMinecraftJava") {
        dependsOn(":prepareVeltisRuntime")
    }
}

// Data and module patches address resources, not code. Only the delta is copied:
// the vanilla jar already carries Minecraft's own resources, and copying them
// again would be a second set of identical bytes that could win over a patched
// one purely on classpath order. `VeltisRuntime.copyResourceDelta` does the same
// thing at runtime, so the two produce the same tree.
val processMinecraftResources = tasks.named<ProcessResources>("processMinecraftResources") {
    group = "minecraft"
    description = "Copies the resources the data and module patches changed"
    from(patchTargets("data"))
    from(patchTargets("modules"))
    destinationDir = resourcesDir.asFile
    dependsOn(":applyVeltisPatches")
}

// ---------------------------------------------------------------------------
// Generated resources packaged into the launcher jar
//
// Two small generated files, both derived from settings that already exist, and
// both generated by the engine rather than by string formatting in a build
// script. They are what lets a single jar be both the launcher and the patch
// distribution.
// ---------------------------------------------------------------------------

/**
 * Records the Minecraft version this jar was built for.
 *
 * <p>So `java -jar veltismc.jar` with no flags has a version to build against,
 * without a constant in launcher source that could drift from the build. A
 * version bump stays a one-line `gradle.properties` change.
 */
val writePackagedVersion by tasks.registering {
    group = "minecraft"
    description = "Records the Minecraft version the launcher jar defaults to"
    val target = packagedVersionFile
    inputs.property("minecraftVersion", minecraftVersion)
    outputs.file(target).withPropertyName("packagedVersion")
    doLast {
        val file = target.get().asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            # Generated by the VeltisMC build. The version java -jar veltismc.jar
            # builds for when --version is not given.
            $minecraftVersion
            """.trimIndent() + "\n"
        )
    }
}

/**
 * Records the minimum Java release the packaged server runs on.
 *
 * <p>Written from the same {@code veltisJavaRelease} the compiler targets, so
 * the runtime version guard the launcher executes and the class files it is
 * about to load are guaranteed to agree. The guard is compiled to Java 8 so it
 * can run on a JVM too old to load anything else in the jar, and it reads this
 * file rather than carrying a constant that could drift.
 */
val writePackagedJavaVersion by tasks.registering {
    group = "minecraft"
    description = "Records the minimum Java release the packaged server is compiled for"
    val target = packagedJavaVersionFile
    inputs.property("veltisJavaRelease", veltisJavaRelease)
    outputs.file(target).withPropertyName("packagedJavaVersion")
    doLast {
        val file = target.get().asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            # Generated by the VeltisMC build. The minimum Java feature release
            # java -jar veltismc.jar runs on; the class files in this jar are
            # compiled for exactly this release. Read by JavaVersionGuard before
            # any other class is loaded.
            $veltisJavaRelease
            """.trimIndent() + "\n"
        )
    }
}

// ---------------------------------------------------------------------------
// Pipeline steps
//
// Every step is a JavaExec with declared inputs and outputs, so Gradle can skip
// work that is genuinely done and rerun work that is not. The steps themselves
// are thin wrappers around patch-engine (see patch-engine/PipelineRunner).
// ---------------------------------------------------------------------------
fun pipelineStep(
    name: String,
    step: String,
    description: String,
) = tasks.register<JavaExec>(name) {
    this.group = "minecraft"
    this.description = description
    classpath = pipelineClasspath
    mainClass = "org.veltismc.patchengine.PipelineRunner"
    javaLauncher.set(pipelineLauncher)
    // patchWorkers is used by the patching step and the release by the compile
    // step; each step ignores the argument it does not use.
    args(step, minecraftVersion, rootDir.absolutePath, patchWorkers.toString(),
        veltisJavaRelease.toString())
    dependsOn(":patch-engine:classes")
    // Any change to the pipeline code itself must invalidate the pipeline's
    // own outputs, otherwise a fix to the patcher would not take effect until
    // something unrelated changed.
    inputs.files(pipelineClasspath).withPropertyName("pipelineClasspath")
    // `-PveltisPipelineDebug` adds the Java stack trace to a failure. The
    // engine's own messages are written to be readable on their own, but a
    // message that comes from deep inside the JDK or a decompiler is not, and
    // without a stack there is nowhere to look. The same flag also turns the
    // pipeline JVMs' root logger to DEBUG: every preparation diagnostic the
    // engine prints is DEBUG (normal server startup shows only the bootstrap
    // lines), and the build's phase timings are behind this flag.
    if (providers.gradleProperty("veltisPipelineDebug").isPresent) {
        systemProperty("veltismc.debug", "true")
        systemProperty("veltis.log.level", "DEBUG")
    }
}

val downloadMinecraft = pipelineStep(
    "downloadMinecraft", "downloadMinecraft",
    "Resolves Minecraft $minecraftVersion on Mojang and verifies every artifact's SHA-1"
).also {
    it.configure {
        inputs.property("minecraftVersion", minecraftVersion)
        // Declaring the manifest URL as an input is what makes a change to the
        // acquisition endpoint re-run the download.
        // The classes jar alongside the bundler jar: it is extracted from the
        // bundler rather than downloaded separately, and it is the baseline the
        // bytecode patch set is cut from, so a build that does not know about it
        // would treat a required input as a stray file.
        outputs.files(versionMetadataFile, libraryCoordinatesFile, vanillaServerJar,
            vanillaClassesJar)
            .withPropertyName("minecraftArtifacts")
    }
}

val downloadLibraries = pipelineStep(
    "downloadLibraries", "downloadLibraries",
    "Fetches the library jars Mojang declares for $minecraftVersion"
).also {
    it.configure {
        inputs.files(versionMetadataFile, libraryCoordinatesFile)
            .withPropertyName("declarationInputs")
        inputs.property("minecraftVersion", minecraftVersion)
        outputs.dir(librariesDir).withPropertyName("minecraftLibraries")
        // Never skipped. Gradle decides a directory output is unchanged by
        // comparing it with its recorded snapshot, and an earlier step recreates
        // libraries/ as an empty directory before this check runs -- so on a fresh
        // clone Gradle saw an empty tree, called it up to date, and the build
        // carried on with no libraries at all. There is no honest predicate
        // available here either: metadata/libraries.txt lists the 56 resolvable
        // module coordinates, not the 114 artifact files actually fetched, so a
        // directory count cannot prove the tree is complete.
        //
        // The step is idempotent and cheap when warm: it SHA-1 verifies each
        // cached jar and fetches nothing, which measures ~370ms. Paying that to
        // remove a way to silently ship an empty classpath is the right trade.
        outputs.upToDateWhen { false }
        dependsOn(downloadMinecraft)
    }
}

/**
 * Widens class, field and method access in the verified class jar.
 *
 * <p>This runs before the decompile, not after it, and that ordering is the
 * whole point: the decompiled source is compiled against the widened jar, so a
 * method Mojang declared `protected` is `public` in both. Decompiling the
 * un-widened jar instead produces sources that cannot be compiled over the
 * widened classes at all — "attempting to assign weaker access privileges" on
 * every override the patch set touches.
 */
val widenServerJarAccess = pipelineStep(
    "widenServerJarAccess", "widenServerJarAccess",
    "Widens class/field/method access in the verified server jar"
).also {
    it.configure {
        // Before the decompile, not after it, and that ordering is the whole
        // point: the decompiled source is compiled against the widened jar, so a
        // method Mojang declared `protected` is `public` in both. Decompiling the
        // un-widened jar instead produces sources that cannot be compiled over the
        // widened classes at all — "attempting to assign weaker access privileges"
        // on every override the patch set touches.
        inputs.file(vanillaClassesJar).withPropertyName("serverClassesJar")
        outputs.file(widenedServerJar).withPropertyName("widenedServerJar")
        dependsOn(downloadMinecraft)
    }
}

val decompileMinecraft = pipelineStep(
    "decompileMinecraft", "decompileMinecraft",
    "Decompiles the verified server jar into the workspace's pristine source tree"
).also {
    it.configure {
        inputs.files(widenedServerJar, libraryCoordinatesFile)
            .withPropertyName("decompileInputs")
        outputs.dir(sourceDir).withPropertyName("decompiledSource")
        dependsOn(downloadLibraries, widenServerJarAccess)
    }
}

val applyVeltisPatches = pipelineStep(
    "applyVeltisPatches", "applyVeltisPatches",
    "Mirrors the decompiled source and applies server/Shulker/{code,data,modules}"
).also {
    it.configure {
        inputs.dir(patchesDir).withPropertyName("patchSet")
        inputs.dir(sourceDir).withPropertyName("decompiledSource")
        inputs.property("minecraftVersion", minecraftVersion)
        inputs.property("patchWorkers", patchWorkers)
        outputs.dir(patchedDir).withPropertyName("patchedSource")
        outputs.file(patchTargetsFile).withPropertyName("patchTargets")
        dependsOn(decompileMinecraft)
    }
}

val rebuildVeltisPatches = pipelineStep(
    "rebuildVeltisPatches", "rebuildVeltisPatches",
    "Regenerates server/Shulker/ from the current contents of the patched workspace"
).also {
    it.configure {
        // Deliberately NOT dependsOn(applyVeltisPatches). The rebuild workflow is
        // "edit a file in patched/ in the IDE, then run this task", and apply
        // re-mirrors the pristine source over patched/ with REPLACE_EXISTING --
        // so depending on it would discard the very edits being captured, and the
        // rebuild would diff a tree it had just overwritten. Only the pristine
        // baseline is needed here, which is decompileMinecraft's output.
        dependsOn(decompileMinecraft)

        // patched/ is hand-edited between runs, so its contents cannot be tracked
        // as an input: Gradle would either miss a change or consider the task up to
        // date while server/Shulker/ is stale. Reading the tree live and always running is
        // the only honest description of what this task does.
        outputs.upToDateWhen { false }
        outputs.dir(patchesDir).withPropertyName("regeneratedPatches")

        // -PpatchName="Improve Entity Logging" names the one patch this rebuild
        // creates instead of the name derived from the target path. A system
        // property rather than a fifth argument so the pipeline's step signature
        // stays (step, version, root, workers) for every other task, and the
        // rebuilder is the one place that decides what a name means.
        providers.gradleProperty("patchName").orNull?.let { requested ->
            systemProperty("veltismc.patchName", requested)
        }
    }
}

val cleanVeltisPatches = pipelineStep(
    "cleanVeltisPatches", "cleanVeltisPatches",
    "Discards the patched workspace and its compiled output"
).also {
    it.configure {
        // A clean task is meaningless if it can be up to date.
        outputs.upToDateWhen { false }
        outputs.dir(patchedDir).withPropertyName("patchedSource")
        outputs.dir(classesDir).withPropertyName("minecraftClasses")
        outputs.dir(resourcesDir).withPropertyName("minecraftResources")
    }
}

/**
 * The two commands a contributor actually types, as aliases of the pipeline's
 * own names.
 *
 * <p>Both spellings run the same task, so nothing is duplicated and nothing can
 * drift: `applyPatches` is `applyVeltisPatches`, and `rebuildPatches` is
 * `rebuildVeltisPatches`. The shorter pair is what CONTRIBUTING.md documents
 * because it is what reads like an instruction; the longer pair stays because
 * CI, the README and the engine's own log lines already use it, and renaming
 * them would break both for no gain.
 */
tasks.register("applyPatches") {
    group = "minecraft"
    description = "Mirrors the pristine decompiled source and applies server/Shulker/{code,data,modules}"
    dependsOn(applyVeltisPatches)
}

tasks.register("rebuildPatches") {
    group = "minecraft"
    description = "Turns edited files under patched/ back into server/Shulker/, renumbered contiguously"
    dependsOn(rebuildVeltisPatches)
}

/**
 * The whole chain, in one call, through the code the launcher runs.
 *
 * <p>This is the build's answer to "make the runtime ready", and it is the same
 * `VeltisRuntime.prepare()` a cold `java -jar veltismc.jar` calls. One
 * implementation, two callers — which is the point. A separate Gradle
 * composition of download/decompile/patch/compile tasks could drift from what a
 * server actually does, and the drift would show up as a jar that builds fine
 * and starts vanilla. The fine-grained tasks below still exist and still run:
 * they are what an IDE and a developer use to walk one stage at a time.
 *
 * <p>The engine keeps its own per-stage validity rules, so this task is skipped
 * only when the marker it writes still matches the version, the artifact hash,
 * the patch revision and the compiler release.
 */
val prepareVeltisRuntime = pipelineStep(
    "prepareVeltisRuntime", "prepareVeltisRuntime",
    "Builds the patched runtime exactly as the launcher does, and records its identity"
).also {
    it.configure {
        inputs.dir(patchesDir).withPropertyName("patchSet")
        inputs.property("minecraftVersion", minecraftVersion)
        inputs.property("patchWorkers", patchWorkers)
        inputs.property("classFileRelease", veltisJavaRelease)
        // The whole workspace is this task's output, because this task can build
        // all of it: it resolves, downloads, verifies, widens, decompiles, patches
        // and compiles for itself, each stage behind its own cache. Declaring only
        // classes/ would leave the download and decompile stages looking like
        // outputs of the per-stage tasks, whose ordering this task does not and
        // should not depend on.
        outputs.dir(vanillaDir).withPropertyName("vanillaArtifacts")
        outputs.dir(metadataDir).withPropertyName("minecraftMetadata")
        outputs.dir(librariesDir).withPropertyName("minecraftLibraries")
        outputs.dir(sourceDir).withPropertyName("decompiledSource")
        outputs.dir(patchedDir).withPropertyName("patchedSource")
        outputs.dir(classesDir).withPropertyName("patchedClasses")
        outputs.dir(resourcesDir).withPropertyName("patchedResources")
        outputs.dir(buildStateDir).withPropertyName("pipelineState")
        outputs.file(runtimeMarkerFile).withPropertyName("runtimeIdentity")
        outputs.dir(runtimePatchesDir).withPropertyName("runtimePatches")
        // The patched runtime artifact: the same jar the launcher runs and the
        // same one :server's classpath hands javac and the IDE. Declared so a
        // deleted or stale artifact re-runs the build instead of the compiler
        // silently reading last week's classes.
        outputs.file(veltisServerJar).withPropertyName("veltisServerJar")

        // The per-stage tasks and this one both produce the workspace, which Gradle
        // will call an overlapping output and refuse to cache. It is a real
        // duplication, and the ordering below is what keeps it harmless: when a
        // developer asks for both in one invocation (`prepareMinecraft
        // buildVeltisMC`) the per-stage chain runs first and this task then finds
        // every stage cached, so it reduces to the compile and the identity. The
        // alternative — making this task depend on the per-stage chain — would
        // mean the launcher and the build no longer share one implementation.
        mustRunAfter(downloadMinecraft, downloadLibraries, widenServerJarAccess,
            decompileMinecraft, applyVeltisPatches, rebuildVeltisPatches)
    }
}

/**
 * Fails the build unless the runtime really loads its patched classes.
 *
 * <p>Replaces the old check that unpacked the pre-packaged server jar and
 * compared bytes. That check could only prove a class was present in an
 * archive; the
 * failure it guards against is a classpath decision — vanilla winning because an
 * entry was ordered differently, or because a library shadowed it. This one
 * builds the loader the server will use and asks it where each patched class
 * resolves from and whether the bytes are patched.
 *
 * <p>Three layers instead of one, because each catches a different mistake:
 * the compiled class exists, it differs from vanilla (so no patch silently
 * applied nothing), and the loader serves exactly those bytes.
 */
val verifyVeltisRuntime = pipelineStep(
    "verifyVeltisRuntime", "verifyVeltisRuntime",
    "Proves the runtime classpath loads the patched classes and not the vanilla ones"
).also {
    it.configure {
        // The classpath input is declared by pipelineStep; only the dependency on
        // what it verifies is this task's own.
        dependsOn(prepareVeltisRuntime)
        // `-PveltisGuardCanary` reverses the classpath on purpose so the guard's
        // failure can be demonstrated rather than asserted. Forwarded explicitly
        // because a Gradle property is not a system property: without this the run
        // reports success and proves nothing, which is the one outcome a canary
        // must never produce.
        if (providers.gradleProperty("veltisGuardCanary").isPresent) {
            systemProperty("veltisGuardCanary", "true")
        }
    }
}

/**
 * Publishes the bytecode patch set into the resources the launcher jar is built
 * from.
 *
 * <p>This is the one thing that makes `java -jar server.jar` a complete
 * distribution: the patch set that turns a downloaded vanilla jar into a
 * VeltisMC server travels inside the launcher, under a name that says which
 * Minecraft version it addresses. An operator never has a `Shulker/` directory,
 * a Git checkout, a decompiler or a compiler, and never needs one.
 *
 * <p>Generated rather than assembled by the packaging script, so the file that
 * ships is the file the applier reads back and re-validates — a patch set that
 * this build could not read would fail here instead of on a stranger's machine.
 */
val publishBytecodePatch by tasks.registering {
    group = "minecraft"
    description = "Publishes the bytecode patch set the launcher jar distributes"
    val source = workspaceDir.file("build/veltis-patch.zip")
    inputs.file(source).withPropertyName("bytecodePatchSet")
    inputs.property("minecraftVersion", minecraftVersion)
    outputs.file(generatedPatchFile).withPropertyName("publishedPatchSet")
    dependsOn(prepareVeltisRuntime)
    doLast {
        val target = generatedPatchFile.get().asFile
        val version = "$minecraftVersion"
        target.parentFile.mkdirs()
        Files.copy(
            source.asFile.toPath(),
            target.toPath(),
            StandardCopyOption.REPLACE_EXISTING,
        )
        logger.lifecycle(
            "Published {} ({} bytes) as META-INF/veltis/patches/{}.zip",
            source.asFile,
            target.length(),
            version,
        )
    }
}

/**
 * The per-stage chain, for an IDE and for a developer working on patches.
 *
 * <p>Not on the production path: `prepareVeltisRuntime` above builds the same
 * result through the engine's own staging, and `compileMinecraftJava` exists so
 * IntelliJ can resolve, navigate and debug the patched sources with a real
 * Gradle compile classpath rather than a folder someone marked by hand.
 */
val prepareMinecraft by tasks.registering {
    group = "minecraft"
    description = "Downloads, decompiles, patches and compiles Minecraft $minecraftVersion (IDE path)"
    dependsOn(applyVeltisPatches, ":compileMinecraftJava", processMinecraftResources)
}

// ---------------------------------------------------------------------------
// Packaging
// ---------------------------------------------------------------------------

/**
 * The distributable: the launcher, with no Minecraft code inside it.
 *
 * <p>One jar, and it is not a build prerequisite for running it. `java -jar
 * veltismc.jar` builds the runtime on first launch and reuses it afterwards, so
 * the same artifact serves a developer, a CI job that wants the work done up
 * front, and an operator who has never seen a Gradle build. `buildVeltisMC` still
 * exists to do that work ahead of time — it is a prebuilder and a release step,
 * not a gate on starting a server.
 */
val packageVeltisMC by tasks.registering(Copy::class) {
    group = "minecraft"
    description = "Packages the EULA-compliant launcher jar (no Minecraft code)"
    from(project(":launcher").tasks.named("uberJar"))
    into(layout.buildDirectory.dir("distributions"))
    rename { "veltismc.jar" }
    dependsOn(":launcher:uberJar")
}

val buildVeltisMC = tasks.register("buildVeltisMC") {
    group = "minecraft"
    description = "Builds the runtime and the launcher jar (optional; the jar self-bootstraps)"
    dependsOn(prepareVeltisRuntime, verifyVeltisRuntime, packageVeltisMC,
        ":launcher:verifyDistributableContent")
    doLast {
        logger.lifecycle("VeltisMC build completed:")
        logger.lifecycle("  launcher: {}", layout.buildDirectory.file("distributions/veltismc.jar").get().asFile)
        logger.lifecycle("  runtime:  {} ({} patched classes)", classesDir.asFile, patchTargetCount("code"))
    }
}

/**
 * The standard `build` produces the distributable jar and verifies the runtime,
 * so a green `build` means a jar that will actually start patched.
 *
 * <p>It does run the runtime preparation, and it has to: `:server` compiles
 * against Minecraft's classes, and the guard has to have a real artifact in order
 * to say anything about one. On a machine that already has the workspace that is
 * a warm validation — a few hundred milliseconds of reading a jar and hashing a
 * file — and on a fresh clone it is the one time the full chain runs, so the
 * first `./gradlew build` costs a download and a decompile and every later one
 * does not. `./gradlew buildVeltisMC` exists for the case where that work is the
 * point rather than a side effect.
 */
tasks.named("build") {
    dependsOn(verifyVeltisRuntime, packageVeltisMC, ":launcher:verifyDistributableContent")
}
