package org.veltismc.server;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.veltismc.patchengine.MinecraftEula;
import org.veltismc.patchengine.VeltisConsole;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Set;

public final class Main {

    /**
     * Assigned in {@link #main} right after logging/console setup: obtaining a
     * logger earlier would initialize Log4j2 before its configuration is in
     * place, which is what produced mixed output patterns and config errors.
     */
    private static Logger LOG;

    private Main() {}

    public static void main(String[] args) {
        // The one logging system (Log4j2) and a UTF-8 console must be ready
        // before any Minecraft class is loaded: vanilla captures System.out and
        // its loggers at class-init time. Both calls no-op when the launcher
        // already ran them.
        VeltisConsole.configureLog4j();
        VeltisConsole.installConsole();
        LOG = LogManager.getLogger(Main.class);

        // The entry point is stated by the launcher, before any preparation:
        // VeltisLauncher.main writes it as raw bootstrap output the moment the
        // console is up, so the line is always the first thing printed and is
        // printed exactly once. This class is reachable only through the
        // launcher (its classloader carries the patched Minecraft runtime that
        // no direct invocation would build), so printing here too would put
        // the line twice into every startup — once before the download and
        // once after the patches.

        var serverHome = resolveHomeDir(args);
        generateServerProperties(serverHome);
        // Refuse an unagreed EULA before the runtime is loaded: no Minecraft
        // class, no world, no download. This is the second of the two places the
        // gate runs -- the launcher checks before it fetches anything at all, and
        // this covers a direct entry into Main. It exits non-zero and prints the
        // exact sentence hosting panels look for.
        MinecraftEula.require(serverHome);
        bootRuntime(args);
        var mcArgs = filterMinecraftArgs(args);
        try {
            net.minecraft.server.Main.main(mcArgs);
        } catch (Exception e) {
            LOG.error("Failed to start Minecraft server", e);
            System.exit(1);
        }
    }

    /**
     * Strips Veltis-only flags so vanilla's option parser only ever sees
     * arguments it actually knows (an unknown option makes vanilla exit).
     */
    private static String[] filterMinecraftArgs(String[] args) {
        var veltisValueFlags = Set.of("--home", "--version", "--protocol", "--name", "--dir", "--max-players");
        var veltisBooleanFlags = Set.of("--verbose");
        var result = new java.util.ArrayList<String>();
        for (int i = 0; i < args.length; i++) {
            var arg = args[i];
            if (veltisBooleanFlags.contains(arg)) continue;
            if (veltisValueFlags.contains(arg)) { i++; continue; }
            result.add(arg);
        }
        return result.toArray(new String[0]);
    }

    private static Path resolveHomeDir(String[] args) {
        for (int i = 0; i < args.length - 1; i++) {
            if ("--home".equals(args[i])) return Path.of(args[i + 1]);
        }
        var home = System.getProperty("veltismc.home");
        if (home != null) return Path.of(home);
        return Path.of(".");
    }

    private static void bootRuntime(String[] args) {
        try {
            Class.forName("org.veltismc.runtime.VeltisBootstrap").getMethod("boot", String[].class).invoke(null, (Object) args);
        } catch (Exception e) {
            LOG.error("Failed to boot VeltisMC runtime", e);
        }
    }

    private static void generateServerProperties(Path homeDir) {
        var propsFile = homeDir.resolve("server.properties");
        if (Files.exists(propsFile)) return;
        try {
            var props = """
                #Minecraft server properties
                #Generated by VeltisMC
                accepts-transfers=false
                allow-flight=false
                broadcast-console-to-ops=true
                broadcast-rcon-to-ops=true
                bug-report-link=
                debug=false
                difficulty=easy
                enable-code-of-conduct=false
                enable-jmx-monitoring=false
                enable-query=false
                enable-rcon=false
                enable-status=true
                enforce-secure-profile=true
                enforce-whitelist=false
                entity-broadcast-range-percentage=100
                force-gamemode=false
                function-permission-level=2
                gamemode=survival
                generate-structures=true
                generator-settings={}
                hardcore=false
                hide-online-players=false
                initial-disabled-packs=
                initial-enabled-packs=vanilla
                level-name=world
                level-seed=
                level-type=minecraft\\:normal
                log-ips=true
                management-server-allowed-origins=
                management-server-enabled=false
                management-server-host=localhost
                management-server-port=0
                management-server-secret=DUUXFvu8PKbR42NpW2U2ZpMXyHolXsRrfmvxlrCl
                management-server-tls-enabled=true
                management-server-tls-keystore=
                management-server-tls-keystore-password=
                max-chained-neighbor-updates=1000000
                max-players=20
                max-tick-time=60000
                max-world-size=29999984
                motd=A Minecraft Server
                network-compression-threshold=256
                online-mode=true
                op-permission-level=4
                pause-when-empty-seconds=-1
                player-idle-timeout=0
                prevent-proxy-connections=false
                query.port=25565
                rate-limit=0
                rcon.password=
                rcon.port=25575
                region-file-compression=deflate
                require-resource-pack=false
                resource-pack=
                resource-pack-id=
                resource-pack-prompt=
                resource-pack-sha1=
                server-ip=
                server-port=25565
                simulation-distance=10
                spawn-protection=16
                status-heartbeat-interval=0
                sync-chunk-writes=true
                text-filtering-config=
                text-filtering-version=0
                use-native-transport=true
                view-distance=10
                white-list=false
                """;
            Files.writeString(propsFile, props, StandardCharsets.UTF_8);
            LOG.debug("Generated server.properties");
        } catch (Exception e) {
            LOG.error("Failed to generate server.properties", e);
        }
    }

}
