package org.veltismc.patchengine;

import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassVisitor;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.FieldVisitor;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.FieldNode;
import org.objectweb.asm.tree.InnerClassNode;
import org.objectweb.asm.tree.MethodNode;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;

/**
 * Builds the runtime class deltas: one per modified class, generated by
 * comparing the compiled class against the verified vanilla class and keeping
 * only the difference.
 *
 * <h2>The comparison</h2>
 *
 * <p>A member of the compiled class counts as <em>unchanged</em> when it is
 * identical to the vanilla member after two normalisations, and as
 * <em>changed</em> otherwise:</p>
 *
 * <ul>
 *   <li><b>Debug information is ignored</b> — line number and local variable
 *       tables come from the compiler's view of the source layout and are
 *       not semantic. Both sides are read with {@link ClassReader#SKIP_DEBUG}
 *       for comparison purposes.</li>
 *   <li><b>Access flags are pushed through {@link AccessWidener}'s widening
 *       transform</b> — {@code source/} was decompiled from the <em>widened</em>
 *       jar, so every class in it has flags the development pipeline changed
 *       before javac ever saw them. A difference that only exists because of
 *       that pre-existing transform is not a change the patch introduced. The
 *       exact same functions the pipeline ran are used here, exemptions
 *       included: enum constructors and static initialisers keep their flags,
 *       interface fields keep {@code final}. A field's constant value is
 *       ignored exactly when widening strips {@code final}, because then the
 *       patched compilation moved the initialiser into {@code <clinit>} —
 *       which the body comparison covers.</li>
 *   <li><b>Everything else must match byte for byte</b> — instructions, stack
 *       map frames, try/catch ranges, maxima, annotations, signatures,
 *       descriptors, unknown attributes. Any of those differing makes the
 *       member carried into the delta in full.</li>
 * </ul>
 *
 * <p>The result is that a member kept as "unchanged" is provably the same
 * code the patched compilation saw, while the delta still never contains its
 * body. Members present only in the compiled class are carried as additions;
 * members present only in the vanilla class become removals; members that
 * compare equal but declare different raw flags become widening records
 * (their bodies stay vanilla's).</p>
 *
 * <h2>Verification</h2>
 *
 * <p>Every delta is applied back onto its vanilla class in two passes: a first
 * pass computes the result hash, the recorded metadata is then filled in with
 * it, and a second full application must reproduce exactly those bytes and
 * pass {@link ClassDelta#apply}'s own hash and fingerprint checks. The merged
 * class is then checked against the <em>compiled</em> class structurally —
 * same header, same class-level metadata, same inner-class and nest-member
 * tables (modulo entries the merged form keeps from vanilla by rule), same
 * members with identical flags and normalisation-equal bodies — so a
 * generation bug that would silently drop a member fails the build instead of
 * shipping. This is the byte-for-byte-plus-structural verification the
 * architecture requires: {@code ApplyDelta(VanillaClass, Delta)} must equal
 * the compiled class wherever the two are meant to agree, and where they are
 * deliberately allowed to differ (debug information on kept members,
 * vanilla-only inner-class entries) the difference is stated and checked, not
 * assumed.</p>
 *
 * <h2>Widening deltas</h2>
 *
 * <p>{@link AccessRequirements} can also ask for vanilla classes the patch
 * never replaces to be rewritten — a header that must become public, one
 * method whose {@code final} blocks an override. Those become deltas too:
 * same format, empty carried/removed lists, and flag records only. No
 * Mojang bytecode, no bodies, no widened class files.</p>
 *
 * <h2>Parallelism and determinism</h2>
 *
 * <p>Comparison, delta construction and verification run on one bounded,
 * fixed-size pool created per generation run from the build's {@code workers}
 * property — never a pool per class, never a parallel stream. Results are
 * collected in submission order over a pre-sorted target list, so the output
 * does not depend on completion order.</p>
 */
public final class ClassDeltaGenerator {

    private ClassDeltaGenerator() {
    }

    /**
     * Timings for one generation run, in nanoseconds.
     *
     * @param comparisonNanos   summed across classes: reading and normalising
     *                          both sides, deciding what changed
     * @param generationNanos   summed: building deltas and the first pass that
     *                          computes each result hash
     * @param verificationNanos summed: the second application and the
     *                          structural check against the compiled class
     * @param totalNanos        wall clock for the whole run
     * @param workers           the pool size the run used
     */
    public record Timings(long comparisonNanos, long generationNanos, long verificationNanos,
                          long totalNanos, int workers) {
    }

    /**
     * What one run produced.
     *
     * @param entries      one entry per class-bearing payload: class deltas for
     *                     classes that exist in vanilla and ordinary additions
     *                     for classes the patch set introduces, sorted by name
     * @param deltaCount   how many entries are class deltas
     * @param unchanged    how many compiled classes were byte-identical to
     *                     vanilla and therefore produced nothing
     * @param timings      how long the phases took
     */
    public record Result(List<BytecodePatch.ProducedEntry> entries, int deltaCount,
                         int unchanged, Timings timings) {
    }

    /** One class's task outcome. */
    private record Outcome(BytecodePatch.ProducedEntry entry, boolean unchanged,
                           long comparisonNanos, long generationNanos,
                           long verificationNanos) {
    }

    // ------------------------------------------------------------------
    // The compiled classes
    // ------------------------------------------------------------------

    /**
     * Generates deltas for every compiled class, comparing each against the
     * vanilla class it was compiled from.
     *
     * @param vanillaClasses     entry name → bytes for the baseline
     * @param compiledClasses    internal name → bytes for javac's output
     * @param minecraftVersion   the version string recorded in each delta
     * @param shulkerFingerprint the source-patch fingerprint recorded in each
     *                           delta, binding it to the patch set it belongs to
     * @param workers            the bounded pool size ({@code 1} runs inline)
     * @return the entries, counts and timings
     * @throws PatchEngineException when a class cannot be read, a delta
     *                               contradicts its baseline, or verification
     *                               fails
     */
    public static Result generate(Map<String, byte[]> vanillaClasses,
                                  Map<String, byte[]> compiledClasses,
                                  String minecraftVersion, String shulkerFingerprint,
                                  int workers) {
        Objects.requireNonNull(vanillaClasses, "vanillaClasses cannot be null");
        Objects.requireNonNull(compiledClasses, "compiledClasses cannot be null");
        var names = new ArrayList<>(new TreeSet<>(compiledClasses.keySet()));
        var poolSize = Math.max(1, workers);
        var started = System.nanoTime();
        var outcomes = new Outcome[names.size()];
        ExecutorService pool = poolSize > 1 && names.size() > 1
            ? Executors.newFixedThreadPool(poolSize) : null;
        try {
            if (pool == null) {
                for (var i = 0; i < names.size(); i++) {
                    outcomes[i] = generateOne(vanillaClasses, compiledClasses, names.get(i),
                        minecraftVersion, shulkerFingerprint);
                }
            } else {
                var futures = new ArrayList<Future<Outcome>>(names.size());
                for (var name : names) {
                    futures.add(pool.submit(() -> generateOne(vanillaClasses, compiledClasses,
                        name, minecraftVersion, shulkerFingerprint)));
                }
                for (var i = 0; i < futures.size(); i++) {
                    try {
                        outcomes[i] = futures.get(i).get();
                    } catch (InterruptedException e) {
                        Thread.currentThread().interrupt();
                        throw new PatchEngineException(
                            "[Veltis] Interrupted while generating class deltas", e);
                    } catch (ExecutionException e) {
                        if (e.getCause() instanceof PatchEngineException patchError) {
                            throw patchError;
                        }
                        throw new PatchEngineException(
                            "[Veltis] Failed to generate a class delta: "
                                + MojangMetadata.rootMessage(e), e);
                    }
                }
            }
        } finally {
            if (pool != null) {
                pool.shutdown();
            }
        }

        var entries = new ArrayList<BytecodePatch.ProducedEntry>();
        long comparison = 0L;
        long generation = 0L;
        long verification = 0L;
        int deltaCount = 0;
        int unchanged = 0;
        for (var outcome : outcomes) {
            comparison += outcome.comparisonNanos();
            generation += outcome.generationNanos();
            verification += outcome.verificationNanos();
            if (outcome.unchanged()) {
                unchanged++;
            } else {
                entries.add(outcome.entry());
                if (outcome.entry().kind() == BytecodePatch.Kind.CLASS) {
                    deltaCount++;
                }
            }
        }
        return new Result(entries, deltaCount, unchanged,
            new Timings(comparison, generation, verification, System.nanoTime() - started,
                poolSize));
    }

    /**
     * Generates one class's delta, or reports that the class needs none.
     */
    private static Outcome generateOne(Map<String, byte[]> vanillaClasses,
                                       Map<String, byte[]> compiledClasses, String name,
                                       String minecraftVersion, String shulkerFingerprint) {
        var compiled = compiledClasses.get(name);
        var vanilla = vanillaClasses.get(name + ".class");
        if (vanilla != null && Arrays.equals(vanilla, compiled)) {
            // Identical to vanilla, so there is no difference to distribute.
            return new Outcome(null, true, 0L, 0L, 0L);
        }
        if (vanilla == null) {
            // A class the patch set introduces: there is no vanilla counterpart
            // to cut a delta against, and nothing Mojang wrote to carry — the
            // compiled bytes are entirely the patch's own content.
            var entry = new BytecodePatch.ProducedEntry(name + ".class", BytecodePatch.Kind.ENTRY,
                compiled, BytecodePatch.ABSENT, BytecodePatch.sha256Hex(compiled));
            return new Outcome(entry, false, 0L, 0L, 0L);
        }

        long phase = System.nanoTime();
        var vanillaNode = parseCompare(vanilla, name);
        var compiledNode = parseCompare(compiled, name);
        var compiledFull = parse(compiled, name);
        var vanillaIsEnum = (vanillaNode.access & Opcodes.ACC_ENUM) != 0;
        var vanillaIsInterface =
            (vanillaNode.access & (Opcodes.ACC_INTERFACE | Opcodes.ACC_ANNOTATION)) != 0;
        var compiledIsEnum = (compiledNode.access & Opcodes.ACC_ENUM) != 0;
        var compiledIsInterface =
            (compiledNode.access & (Opcodes.ACC_INTERFACE | Opcodes.ACC_ANNOTATION)) != 0;

        var carriedFields = new ArrayList<FieldNode>();
        var carriedMethods = new ArrayList<MethodNode>();
        var removed = new ArrayList<ClassDelta.MemberRef>();
        var widened = new ArrayList<ClassDelta.WidenedMember>();
        classifyFields(vanillaNode, compiledNode, vanillaIsInterface, compiledIsInterface,
            carriedFields, removed, widened);
        classifyMethods(vanillaNode, compiledNode, vanillaIsEnum, compiledIsEnum,
            carriedMethods, removed, widened);
        long comparisonNanos = System.nanoTime() - phase;

        // First pass: the delta with placeholder result hashes. Applying it
        // computes the merged bytes whose hash the metadata must record.
        long generationStarted = System.nanoTime();
        var vanillaSha = BytecodePatch.sha256Hex(vanilla);
        var target = name;
        var placeholder = ClassDelta.placeholderHash();
        var firstMeta = new ClassDelta.Metadata(ClassDelta.FORMAT, minecraftVersion, target,
            vanillaSha, placeholder, shulkerFingerprint, placeholder, removed, widened);
        var deltaNode = buildDelta(compiledFull, carriedFields, carriedMethods, firstMeta);
        var firstPass = ClassDelta.applyForGeneration(vanilla, serialize(deltaNode));
        var merged = firstPass.bytes();
        long generationNanos = System.nanoTime() - generationStarted;

        // Second pass: fill in the hashes the first pass produced, then run
        // the full apply — hash, fingerprint, and byte-for-byte determinism —
        // and check the result structurally against the compiled class.
        long verificationStarted = System.nanoTime();
        var patchedSha = BytecodePatch.sha256Hex(merged);
        var fingerprint = ClassDelta.classPatchFingerprint(vanillaSha, patchedSha, target);
        var finalMeta = new ClassDelta.Metadata(ClassDelta.FORMAT, minecraftVersion, target,
            vanillaSha, patchedSha, shulkerFingerprint, fingerprint, removed, widened);
        deltaNode.attrs = new ArrayList<>(List.of(ClassDelta.attribute(finalMeta)));
        var deltaBytes = serialize(deltaNode);
        var applied = ClassDelta.apply(vanilla, deltaBytes);
        if (!Arrays.equals(applied.bytes(), merged)) {
            throw mismatch(target, "is not deterministic: applying it twice produced different"
                + " bytes",
                "the delta was built from unstable inputs; a patch set that changes between"
                    + " identical builds cannot be verified by hash");
        }
        verifyStructural(applied.bytes(), compiled, target);
        long verificationNanos = System.nanoTime() - verificationStarted;

        var entry = new BytecodePatch.ProducedEntry(target + ".class", BytecodePatch.Kind.CLASS,
            deltaBytes, vanillaSha, patchedSha);
        return new Outcome(entry, false, comparisonNanos, generationNanos, verificationNanos);
    }

    // ------------------------------------------------------------------
    // Classification
    // ------------------------------------------------------------------

    private static void classifyFields(ClassNode vanilla, ClassNode compiled,
                                       boolean vanillaIsInterface, boolean compiledIsInterface,
                                       List<FieldNode> carried,
                                       List<ClassDelta.MemberRef> removed,
                                       List<ClassDelta.WidenedMember> widened) {
        var vanillaFields = indexFields(vanilla.fields);
        var compiledKeys = new HashSet<ClassDelta.MemberRef>();
        for (var field : compiled.fields) {
            var key = new ClassDelta.MemberRef(true, field.name, field.desc);
            compiledKeys.add(key);
            var vanillaField = vanillaFields.get(key);
            if (vanillaField == null) {
                carried.add(field);
                continue;
            }
            var same = Arrays.equals(
                canonicalField(vanillaField, vanillaIsInterface),
                canonicalField(field, compiledIsInterface));
            if (!same) {
                carried.add(field);
            } else if (vanillaField.access != field.access) {
                widened.add(new ClassDelta.WidenedMember(true, field.name, field.desc,
                    field.access));
            }
        }
        for (var key : vanillaFields.keySet()) {
            if (!compiledKeys.contains(key)) {
                removed.add(key);
            }
        }
    }

    private static void classifyMethods(ClassNode vanilla, ClassNode compiled,
                                        boolean vanillaIsEnum, boolean compiledIsEnum,
                                        List<MethodNode> carried,
                                        List<ClassDelta.MemberRef> removed,
                                        List<ClassDelta.WidenedMember> widened) {
        var vanillaMethods = indexMethods(vanilla.methods);
        var compiledKeys = new HashSet<ClassDelta.MemberRef>();
        for (var method : compiled.methods) {
            var key = new ClassDelta.MemberRef(false, method.name, method.desc);
            compiledKeys.add(key);
            var vanillaMethod = vanillaMethods.get(key);
            if (vanillaMethod == null) {
                carried.add(method);
                continue;
            }
            var same = Arrays.equals(
                canonicalMethod(vanillaMethod, vanillaIsEnum),
                canonicalMethod(method, compiledIsEnum));
            if (!same) {
                carried.add(method);
            } else if (vanillaMethod.access != method.access) {
                widened.add(new ClassDelta.WidenedMember(false, method.name, method.desc,
                    method.access));
            }
        }
        for (var key : vanillaMethods.keySet()) {
            if (!compiledKeys.contains(key)) {
                removed.add(key);
            }
        }
    }

    private static Map<ClassDelta.MemberRef, FieldNode> indexFields(List<FieldNode> fields) {
        var byKey = new HashMap<ClassDelta.MemberRef, FieldNode>();
        for (var field : fields) {
            byKey.put(new ClassDelta.MemberRef(true, field.name, field.desc), field);
        }
        return byKey;
    }

    private static Map<ClassDelta.MemberRef, MethodNode> indexMethods(List<MethodNode> methods) {
        var byKey = new HashMap<ClassDelta.MemberRef, MethodNode>();
        for (var method : methods) {
            byKey.put(new ClassDelta.MemberRef(false, method.name, method.desc), method);
        }
        return byKey;
    }

    // ------------------------------------------------------------------
    // Canonical member bytes
    // ------------------------------------------------------------------

    /**
     * A fixed-header class node holding nothing, used to serialise one member
     * in isolation so constant-pool layout and class context cannot leak into
     * a comparison.
     */
    private static ClassNode memberShell() {
        var shell = new ClassNode();
        shell.version = Opcodes.V21;
        shell.access = Opcodes.ACC_PUBLIC;
        shell.name = "MemberShell";
        shell.superName = "java/lang/Object";
        shell.interfaces = new ArrayList<>();
        shell.innerClasses = new ArrayList<>();
        shell.fields = new ArrayList<>();
        shell.methods = new ArrayList<>();
        return shell;
    }

    private static byte[] serializeShell(ClassNode shell) {
        var writer = new ClassWriter(0);
        shell.accept(writer);
        return writer.toByteArray();
    }

    /**
     * The field's bytes after the normalisation {@link ClassDeltaGenerator}'s
     * class javadoc describes: widened flags, and no constant value once those
     * flags no longer include {@code final}. Two fields serialise the same
     * here exactly when they count as unchanged.
     */
    private static byte[] canonicalField(FieldNode field, boolean ownerKeepsFinal) {
        var shell = memberShell();
        shell.fields.add(field);
        var writer = new ClassWriter(0);
        shell.accept(new ClassVisitor(Opcodes.ASM9, writer) {
            @Override
            public FieldVisitor visitField(int access, String name, String descriptor,
                                           String signature, Object value) {
                var normalized = AccessWidener.widenAll(access, ownerKeepsFinal);
                if ((normalized & Opcodes.ACC_FINAL) == 0) {
                    value = null;
                }
                return super.visitField(normalized, name, descriptor, signature, value);
            }
        });
        return writer.toByteArray();
    }

    /**
     * The method's bytes after the same normalisation: widened flags (with the
     * enum-constructor and static-initialiser exemptions) and no line number
     * or local variable table, because both were parsed away already.
     */
    private static byte[] canonicalMethod(MethodNode method, boolean ownerIsEnum) {
        var shell = memberShell();
        shell.methods.add(method);
        var writer = new ClassWriter(0);
        shell.accept(new ClassVisitor(Opcodes.ASM9, writer) {
            @Override
            public MethodVisitor visitMethod(int access, String name, String descriptor,
                                             String signature, String[] exceptions) {
                var normalized = AccessWidener.widenMethod(access, ownerIsEnum, name);
                return super.visitMethod(normalized, name, descriptor, signature, exceptions);
            }
        });
        return writer.toByteArray();
    }

    // ------------------------------------------------------------------
    // Building a delta node
    // ------------------------------------------------------------------

    private static ClassNode buildDelta(ClassNode compiled, List<FieldNode> carriedFields,
                                        List<MethodNode> carriedMethods,
                                        ClassDelta.Metadata metadata) {
        var delta = new ClassNode();
        delta.version = compiled.version;
        delta.access = compiled.access;
        delta.name = compiled.name;
        delta.superName = compiled.superName;
        delta.interfaces =
            compiled.interfaces != null ? compiled.interfaces : new ArrayList<>();
        ClassDelta.copyScalars(compiled, delta);
        delta.innerClasses = compiled.innerClasses != null ? compiled.innerClasses : new ArrayList<>();
        delta.nestMembers = compiled.nestMembers;
        delta.fields = new ArrayList<>(carriedFields);
        delta.methods = new ArrayList<>(carriedMethods);
        delta.attrs = new ArrayList<>(List.of(ClassDelta.attribute(metadata)));
        return delta;
    }

    private static byte[] serialize(ClassNode node) {
        var writer = new ClassWriter(0);
        node.accept(writer);
        return writer.toByteArray();
    }

    // ------------------------------------------------------------------
    // Verification
    // ------------------------------------------------------------------

    /**
     * Checks the merged class against the compiled class, structurally and
     * member by member: the two must agree on the header, on class-level
     * metadata, on the inner-class and nest-member tables (after dropping the
     * vanilla-only entries the merge keeps by rule), and on every member's
     * flags and normalisation-equal body. Debug information is deliberately
     * not compared — kept members carry vanilla's, and that difference is
     * documented rather than hidden.
     */
    private static void verifyStructural(byte[] mergedBytes, byte[] compiledBytes,
                                         String target) {
        var merged = parseCompare(mergedBytes, target);
        var compiled = parseCompare(compiledBytes, target);
        verifyHeader(merged, compiled, target);
        if (!Arrays.equals(ClassDelta.scalarShell(merged), ClassDelta.scalarShell(compiled))) {
            throw mismatch(target, "produced a class whose metadata differs from the compiled"
                + " class",
                "signature, annotations, source, module or record components did not survive"
                    + " the merge; shipping the delta would change the class's declared"
                    + " metadata as well as its code");
        }
        verifyInnerClasses(merged, compiled, target);
        verifyNestMembers(merged, compiled, target);
        verifyMembers(merged, compiled, target);
    }

    private static void verifyHeader(ClassNode merged, ClassNode compiled, String target) {
        if (merged.version != compiled.version) {
            throw mismatch(target, "produced a class with version " + merged.version
                    + " but the compiled class is version " + compiled.version,
                "the delta header must be the compiled class's header verbatim");
        }
        if (merged.access != compiled.access) {
            throw mismatch(target, "produced a class with access flags 0x"
                    + Integer.toHexString(merged.access) + " but the compiled class has 0x"
                    + Integer.toHexString(compiled.access),
                "the delta header must be the compiled class's header verbatim, or patched"
                    + " code will resolve the class differently than it compiled against");
        }
        if (!Objects.equals(merged.name, compiled.name)
                || !Objects.equals(merged.superName, compiled.superName)
                || !Objects.equals(merged.interfaces, compiled.interfaces)) {
            throw mismatch(target, "produced a class whose name, superclass or interfaces"
                    + " differ from the compiled class",
                "the delta header must be the compiled class's header verbatim");
        }
    }

    private static void verifyInnerClasses(ClassNode merged, ClassNode compiled, String target) {
        var expected = compiled.innerClasses == null ? List.<InnerClassNode>of()
            : compiled.innerClasses;
        var expectedNames = new HashSet<String>();
        for (var entry : expected) {
            expectedNames.add(entry.name);
        }
        var actual = new ArrayList<InnerClassNode>();
        if (merged.innerClasses != null) {
            for (var entry : merged.innerClasses) {
                if (expectedNames.contains(entry.name)) {
                    actual.add(entry);
                }
            }
        }
        if (actual.size() != expected.size()) {
            throw mismatch(target, "produced a class with " + actual.size()
                    + " inner-class entries for the compiled class's " + expected.size(),
                "the merge must keep exactly the compiled class's entries plus vanilla-only"
                    + " ones; entries were lost or duplicated");
        }
        for (var i = 0; i < expected.size(); i++) {
            var want = expected.get(i);
            var got = actual.get(i);
            if (!Objects.equals(want.name, got.name)
                    || !Objects.equals(want.outerName, got.outerName)
                    || !Objects.equals(want.innerName, got.innerName)
                    || want.access != got.access) {
                throw mismatch(target, "produced an inner-class entry for " + want.name
                        + " with access 0x" + Integer.toHexString(got.access)
                        + ", compiled has 0x" + Integer.toHexString(want.access),
                    "inner-class entries decide the runtime's access check for the nested"
                        + " class; they must match what the patched compilation saw");
            }
        }
    }

    private static void verifyNestMembers(ClassNode merged, ClassNode compiled, String target) {
        var expected = compiled.nestMembers == null ? List.<String>of() : compiled.nestMembers;
        var expectedSet = new HashSet<>(expected);
        var actual = new ArrayList<String>();
        if (merged.nestMembers != null) {
            for (var member : merged.nestMembers) {
                if (expectedSet.contains(member)) {
                    actual.add(member);
                }
            }
        }
        if (!actual.equals(expected)) {
            throw mismatch(target, "produced nest members " + actual + " but the compiled class"
                    + " declares " + expected,
                "nest membership decides which private members link; the merge must keep the"
                    + " compiled class's list");
        }
    }

    private static void verifyMembers(ClassNode merged, ClassNode compiled, String target) {
        var mergedIsEnum = (compiled.access & Opcodes.ACC_ENUM) != 0;
        var mergedIsInterface =
            (compiled.access & (Opcodes.ACC_INTERFACE | Opcodes.ACC_ANNOTATION)) != 0;
        var mergedFields = new TreeMap<ClassDelta.MemberRef, FieldNode>(MEMBER_ORDER);
        for (var field : merged.fields) {
            mergedFields.put(new ClassDelta.MemberRef(true, field.name, field.desc), field);
        }
        var compiledFields = new TreeMap<ClassDelta.MemberRef, FieldNode>(MEMBER_ORDER);
        for (var field : compiled.fields) {
            compiledFields.put(new ClassDelta.MemberRef(true, field.name, field.desc), field);
        }
        verifyKeySets(mergedFields.keySet(), compiledFields.keySet(), target, true);
        for (var entry : compiledFields.entrySet()) {
            var key = entry.getKey();
            var got = mergedFields.get(key);
            var want = entry.getValue();
            if (got.access != want.access) {
                throw mismatch(target, "declares field " + key.name() + key.desc()
                        + " with access 0x" + Integer.toHexString(got.access)
                        + " but the compiled class has 0x" + Integer.toHexString(want.access),
                    "the merge must give every kept member exactly the compiled class's flags,"
                        + " or patched code resolves it differently than it compiled against");
            }
            if (!Arrays.equals(canonicalField(got, mergedIsInterface),
                    canonicalField(want, mergedIsInterface))) {
                throw mismatch(target, "produced a field " + key.name() + key.desc()
                        + " that differs from the compiled class after normalisation",
                    "a kept member's vanilla body must equal the compiled member's, and a"
                        + " carried member must be the compiled member verbatim");
            }
        }

        var mergedMethods = new TreeMap<ClassDelta.MemberRef, MethodNode>(MEMBER_ORDER);
        for (var method : merged.methods) {
            mergedMethods.put(new ClassDelta.MemberRef(false, method.name, method.desc), method);
        }
        var compiledMethods = new TreeMap<ClassDelta.MemberRef, MethodNode>(MEMBER_ORDER);
        for (var method : compiled.methods) {
            compiledMethods.put(new ClassDelta.MemberRef(false, method.name, method.desc), method);
        }
        verifyKeySets(mergedMethods.keySet(), compiledMethods.keySet(), target, false);
        for (var entry : compiledMethods.entrySet()) {
            var key = entry.getKey();
            var got = mergedMethods.get(key);
            var want = entry.getValue();
            if (got.access != want.access) {
                throw mismatch(target, "declares method " + key.name() + key.desc()
                        + " with access 0x" + Integer.toHexString(got.access)
                        + " but the compiled class has 0x" + Integer.toHexString(want.access),
                    "the merge must give every kept member exactly the compiled class's flags,"
                        + " or patched code resolves it differently than it compiled against");
            }
            if (!Arrays.equals(canonicalMethod(got, mergedIsEnum),
                    canonicalMethod(want, mergedIsEnum))) {
                throw mismatch(target, "produced a method " + key.name() + key.desc()
                        + " that differs from the compiled class after normalisation",
                    "a kept member's vanilla body must equal the compiled member's, and a"
                        + " carried member must be the compiled member verbatim");
            }
        }
    }

    private static void verifyKeySets(Set<ClassDelta.MemberRef> actual,
                                      Set<ClassDelta.MemberRef> expected, String target,
                                      boolean fields) {
        for (var key : expected) {
            if (!actual.contains(key)) {
                throw mismatch(target, "is missing the " + (fields ? "field " : "method ")
                        + key.name() + key.desc() + " the compiled class declares",
                    "the merge must produce exactly the compiled class's member set; a lost"
                        + " member breaks whoever the patched code compiled against it");
            }
        }
        for (var key : actual) {
            if (!expected.contains(key)) {
                throw mismatch(target, "declares the " + (fields ? "field " : "method ")
                        + key.name() + key.desc() + ", which the compiled class does not",
                    "the merge must produce exactly the compiled class's member set; an extra"
                        + " member means the delta carried something the patch did not compile");
            }
        }
    }

    private static final Comparator<ClassDelta.MemberRef> MEMBER_ORDER =
        Comparator.comparing(ClassDelta.MemberRef::name)
            .thenComparing(ClassDelta.MemberRef::desc);

    // ------------------------------------------------------------------
    // Widening deltas
    // ------------------------------------------------------------------

    /**
     * Generates flag-only deltas for the vanilla classes {@link AccessRequirements}
     * marked as needing rewrites. Each delta's header and inner-class entries
     * change when the class itself needed widening, and every flagged member
     * gets its recorded flags; bodies are never carried — the merged class is
     * the vanilla class with those flags rewritten, which is verified the same
     * way a compiled class's delta is.
     *
     * @param vanillaClasses     entry name → bytes for the baseline
     * @param analysis           which classes and members need rewriting
     * @param minecraftVersion   the version string recorded in each delta
     * @param shulkerFingerprint the source-patch fingerprint recorded in each
     * @return one class-delta entry per target, sorted by name
     */
    public static List<BytecodePatch.ProducedEntry> wideningDeltas(
            Map<String, byte[]> vanillaClasses, AccessRequirements.Result analysis,
            String minecraftVersion, String shulkerFingerprint) {
        Objects.requireNonNull(vanillaClasses, "vanillaClasses cannot be null");
        Objects.requireNonNull(analysis, "analysis cannot be null");
        var targets = new TreeSet<String>(analysis.wideningRequired());
        targets.addAll(analysis.memberWidenings().keySet());
        var entries = new ArrayList<BytecodePatch.ProducedEntry>();
        for (var target : targets) {
            var vanilla = vanillaClasses.get(target + ".class");
            if (vanilla == null) {
                continue;
            }
            entries.add(wideningDelta(vanilla, target, analysis.wideningRequired().contains(target),
                analysis.memberWidenings().getOrDefault(target, List.of()),
                minecraftVersion, shulkerFingerprint));
        }
        return entries;
    }

    private static BytecodePatch.ProducedEntry wideningDelta(byte[] vanillaBytes, String target,
                                                             boolean widenHeader,
                                                             List<AccessRequirements.MemberWidening> records,
                                                             String minecraftVersion,
                                                             String shulkerFingerprint) {
        var vanillaNode = parse(vanillaBytes, target);
        var isEnum = (vanillaNode.access & Opcodes.ACC_ENUM) != 0;
        var isInterface =
            (vanillaNode.access & (Opcodes.ACC_INTERFACE | Opcodes.ACC_ANNOTATION)) != 0;
        var widened = new ArrayList<ClassDelta.WidenedMember>(records.size());
        for (var record : records) {
            var access = memberAccess(vanillaNode, record);
            int rewritten;
            if (record.finalStrip()) {
                if ((access & Opcodes.ACC_FINAL) == 0) {
                    throw mismatch(target, "cannot drop final from member " + record.name()
                            + record.desc() + " because the vanilla class does not declare it"
                            + " final",
                        "the analysis and the vanilla jar disagree about the same bytes;"
                            + " the patch set cannot be cut from them");
                }
                rewritten = access & ~Opcodes.ACC_FINAL;
            } else if (record.field()) {
                rewritten = AccessWidener.widenAll(access, isInterface);
            } else {
                rewritten = AccessWidener.widenMethod(access, isEnum, record.name());
            }
            if (rewritten == access) {
                throw mismatch(target, "needs member " + record.name() + record.desc()
                        + " widened, but its flags are fixed by the class file format"
                        + " (current flags: 0x" + Integer.toHexString(access) + ")",
                    "an enum constructor must stay non-public and a static initialiser must"
                        + " stay package-private; widening either produces a class file the JVM"
                        + " rejects, so the reference cannot be served"
                        + "\n  Fix: avoid the reference that requires this widening");
            }
            widened.add(new ClassDelta.WidenedMember(record.field(), record.name(),
                record.desc(), rewritten));
        }

        var vanillaSha = BytecodePatch.sha256Hex(vanillaBytes);
        var placeholder = ClassDelta.placeholderHash();
        var deltaNode = buildWideningDelta(vanillaNode, widenHeader, widened,
            new ClassDelta.Metadata(ClassDelta.FORMAT, minecraftVersion, target, vanillaSha,
                placeholder, shulkerFingerprint, placeholder, List.of(), widened));
        var firstPass = ClassDelta.applyForGeneration(vanillaBytes, serialize(deltaNode));
        var merged = firstPass.bytes();
        var patchedSha = BytecodePatch.sha256Hex(merged);
        var fingerprint = ClassDelta.classPatchFingerprint(vanillaSha, patchedSha, target);
        var finalMeta = new ClassDelta.Metadata(ClassDelta.FORMAT, minecraftVersion, target,
            vanillaSha, patchedSha, shulkerFingerprint, fingerprint, List.of(), widened);
        deltaNode.attrs = new ArrayList<>(List.of(ClassDelta.attribute(finalMeta)));
        var deltaBytes = serialize(deltaNode);
        var applied = ClassDelta.apply(vanillaBytes, deltaBytes);
        if (!Arrays.equals(applied.bytes(), merged)) {
            throw mismatch(target, "is not deterministic: applying it twice produced different"
                + " bytes",
                "the widening delta was built from unstable inputs");
        }
        verifyWideningOnly(applied.bytes(), vanillaBytes, target, widenHeader, widened);
        return new BytecodePatch.ProducedEntry(target + ".class", BytecodePatch.Kind.CLASS,
            deltaBytes, vanillaSha, patchedSha);
    }

    private static ClassNode buildWideningDelta(ClassNode vanilla, boolean widenHeader,
                                                List<ClassDelta.WidenedMember> widened,
                                                ClassDelta.Metadata metadata) {
        var delta = new ClassNode();
        delta.version = vanilla.version;
        delta.access = widenHeader ? AccessWidener.widenClassAccess(vanilla.access)
            : vanilla.access;
        delta.name = vanilla.name;
        delta.signature = vanilla.signature;
        delta.superName = vanilla.superName;
        delta.interfaces = vanilla.interfaces != null ? vanilla.interfaces : new ArrayList<>();
        ClassDelta.copyScalars(vanilla, delta);
        delta.innerClasses = widenInnerEntries(vanilla.innerClasses);
        delta.nestMembers = vanilla.nestMembers;
        delta.fields = new ArrayList<>();
        delta.methods = new ArrayList<>();
        delta.attrs = new ArrayList<>(List.of(ClassDelta.attribute(metadata)));
        return delta;
    }

    /**
     * Mirrors {@link AccessWidener}'s treatment of inner-class entries: when a
     * class's header widens, so do the entries its own class file records for
     * its nested classes — the entries are what the compiler and the runtime
     * consult for a nested class's access.
     */
    private static List<InnerClassNode> widenInnerEntries(List<InnerClassNode> entries) {
        if (entries == null) {
            return null;
        }
        var widened = new ArrayList<InnerClassNode>(entries.size());
        for (var entry : entries) {
            widened.add(new InnerClassNode(entry.name, entry.outerName, entry.innerName,
                AccessWidener.widenAll(entry.access, false)));
        }
        return widened;
    }

    private static int memberAccess(ClassNode vanilla, AccessRequirements.MemberWidening record) {
        if (record.field()) {
            for (var field : vanilla.fields) {
                if (field.name.equals(record.name()) && field.desc.equals(record.desc())) {
                    return field.access;
                }
            }
        } else {
            for (var method : vanilla.methods) {
                if (method.name.equals(record.name()) && method.desc.equals(record.desc())) {
                    return method.access;
                }
            }
        }
        throw mismatch(vanilla.name, "needs member " + record.name() + record.desc()
                + " rewritten, which the vanilla class does not declare",
            "the analysis and the vanilla jar disagree about the same bytes; the patch set"
                + " cannot be cut from them");
    }

    /**
     * Verifies a widening delta the way a compiled class's delta is verified,
     * against the vanilla class instead of a compiled one: the merged class
     * must be the vanilla class — same header version, name, superclass,
     * interfaces, metadata, nest members and member bodies — with exactly the
     * documented flag changes: the rewritten header, the rewritten
     * inner-class entries, and the recorded member flags.
     */
    private static void verifyWideningOnly(byte[] mergedBytes, byte[] vanillaBytes,
                                           String target, boolean widenHeader,
                                           List<ClassDelta.WidenedMember> widened) {
        var merged = parseCompare(mergedBytes, target);
        var vanilla = parseCompare(vanillaBytes, target);
        var expectedHeader = widenHeader ? AccessWidener.widenClassAccess(vanilla.access)
            : vanilla.access;
        if (merged.version != vanilla.version
                || !Objects.equals(merged.name, vanilla.name)
                || !Objects.equals(merged.superName, vanilla.superName)
                || !Objects.equals(merged.interfaces, vanilla.interfaces)) {
            throw mismatch(target, "produced a header that differs from the vanilla class in"
                    + " more than its access flags",
                "a widening delta rewrites flags and nothing else");
        }
        if (merged.access != expectedHeader) {
            throw mismatch(target, "produced access flags 0x"
                    + Integer.toHexString(merged.access) + " but expected 0x"
                    + Integer.toHexString(expectedHeader),
                "the header must be the vanilla flags with exactly the required widening");
        }
        if (!Arrays.equals(ClassDelta.scalarShell(merged), ClassDelta.scalarShell(vanilla))) {
            throw mismatch(target, "produced class metadata that differs from the vanilla"
                    + " class",
                "a widening delta rewrites flags and nothing else");
        }
        var vanillaEntries = vanilla.innerClasses;
        var mergedEntries = merged.innerClasses;
        var expectedEntryCount = vanillaEntries == null ? 0 : vanillaEntries.size();
        var actualEntryCount = mergedEntries == null ? 0 : mergedEntries.size();
        if (actualEntryCount != expectedEntryCount) {
            throw mismatch(target, "produced " + actualEntryCount + " inner-class entries but"
                    + " the vanilla class has " + expectedEntryCount,
                "a widening delta rewrites flags and nothing else");
        }
        for (var i = 0; i < expectedEntryCount; i++) {
            var want = vanillaEntries.get(i);
            var got = mergedEntries.get(i);
            var wantAccess = widenHeader ? AccessWidener.widenAll(want.access, false)
                : want.access;
            if (!Objects.equals(want.name, got.name)
                    || !Objects.equals(want.outerName, got.outerName)
                    || !Objects.equals(want.innerName, got.innerName)
                    || wantAccess != got.access) {
                throw mismatch(target, "produced an inner-class entry for " + want.name
                        + " with access 0x" + Integer.toHexString(got.access)
                        + " but expected 0x" + Integer.toHexString(wantAccess),
                    "inner-class entries change only when the class's own header widens");
            }
        }
        if (!Objects.equals(merged.nestMembers, vanilla.nestMembers)
                && !Objects.equals(merged.nestMembers == null ? List.of() : merged.nestMembers,
                    vanilla.nestMembers == null ? List.of() : vanilla.nestMembers)) {
            throw mismatch(target, "produced nest members " + merged.nestMembers
                    + " but the vanilla class declares " + vanilla.nestMembers,
                "a widening delta rewrites flags and nothing else");
        }

        var records = new HashMap<ClassDelta.MemberRef, Integer>();
        for (var record : widened) {
            records.put(new ClassDelta.MemberRef(record.field(), record.name(), record.desc()),
                record.access());
        }
        if (merged.fields.size() != vanilla.fields.size()
                || merged.methods.size() != vanilla.methods.size()) {
            throw mismatch(target, "produced a different member count than the vanilla class"
                    + " (" + merged.fields.size() + "/" + merged.methods.size() + " vs "
                    + vanilla.fields.size() + "/" + vanilla.methods.size() + ")",
                "a widening delta rewrites flags and nothing else");
        }
        var isEnum = (vanilla.access & Opcodes.ACC_ENUM) != 0;
        var isInterface =
            (vanilla.access & (Opcodes.ACC_INTERFACE | Opcodes.ACC_ANNOTATION)) != 0;
        for (var i = 0; i < vanilla.fields.size(); i++) {
            var want = vanilla.fields.get(i);
            var got = merged.fields.get(i);
            var key = new ClassDelta.MemberRef(true, want.name, want.desc);
            if (!Objects.equals(want.name, got.name) || !Objects.equals(want.desc, got.desc)) {
                throw mismatch(target, "produced a different member order than the vanilla"
                        + " class",
                    "with no carried members the merged member list must be the vanilla list");
            }
            var expectedAccess = records.getOrDefault(key, want.access);
            if (got.access != expectedAccess) {
                throw mismatch(target, "declares field " + want.name + want.desc
                        + " with access 0x" + Integer.toHexString(got.access)
                        + " but expected 0x" + Integer.toHexString(expectedAccess),
                    "the delta's recorded flags must be applied verbatim");
            }
            if (!Arrays.equals(canonicalField(got, isInterface),
                    canonicalField(want, isInterface))) {
                throw mismatch(target, "produced field " + want.name + want.desc
                        + " whose definition differs from the vanilla class",
                    "a widening delta rewrites flags and nothing else");
            }
        }
        for (var i = 0; i < vanilla.methods.size(); i++) {
            var want = vanilla.methods.get(i);
            var got = merged.methods.get(i);
            var key = new ClassDelta.MemberRef(false, want.name, want.desc);
            if (!Objects.equals(want.name, got.name) || !Objects.equals(want.desc, got.desc)) {
                throw mismatch(target, "produced a different member order than the vanilla"
                        + " class",
                    "with no carried members the merged member list must be the vanilla list");
            }
            var expectedAccess = records.getOrDefault(key, want.access);
            if (got.access != expectedAccess) {
                throw mismatch(target, "declares method " + want.name + want.desc
                        + " with access 0x" + Integer.toHexString(got.access)
                        + " but expected 0x" + Integer.toHexString(expectedAccess),
                    "the delta's recorded flags must be applied verbatim");
            }
            if (!Arrays.equals(canonicalMethod(got, isEnum),
                    canonicalMethod(want, isEnum))) {
                throw mismatch(target, "produced method " + want.name + want.desc
                        + " whose definition differs from the vanilla class",
                    "a widening delta rewrites flags and nothing else");
            }
        }
    }

    // ------------------------------------------------------------------
    // Parsing
    // ------------------------------------------------------------------

    private static ClassNode parse(byte[] bytes, String target) {
        var node = new ClassNode();
        try {
            new ClassReader(bytes).accept(node, 0);
        } catch (RuntimeException e) {
            throw mismatch(target, "cannot be read as a class file",
                MojangMetadata.rootMessage(e));
        }
        return node;
    }

    /** Parses without debug information, for comparison and verification. */
    private static ClassNode parseCompare(byte[] bytes, String target) {
        var node = new ClassNode();
        try {
            new ClassReader(bytes).accept(node, ClassReader.SKIP_DEBUG);
        } catch (RuntimeException e) {
            throw mismatch(target, "cannot be read as a class file",
                MojangMetadata.rootMessage(e));
        }
        return node;
    }

    private static PatchEngineException mismatch(String target, String detail, String reason) {
        return new PatchEngineException(
            "[Veltis] The class delta for " + target + " " + detail
                + "\n  Reason: " + reason
                + "\n  The patch set was not written."
                + "\n  Fix: regenerate the patch set.");
    }
}
