package org.veltismc.patchengine;

import java.util.Objects;
import java.util.regex.Pattern;

/**
 * A Minecraft version, always owned by exactly one {@link VeltisWorkspace}.
 *
 * <p>Parsed from the {@code minecraftVersion} Gradle property so a version bump
 * is a one-line change and never a hardcoded URL anywhere in the pipeline.
 */
public final class MinecraftVersion implements Comparable<MinecraftVersion> {

    private static final Pattern PATTERN =
        Pattern.compile("^(\\d+)\\.(\\d+)(?:\\.(\\d+))?$");

    private final int major;
    private final int minor;
    private final int patch;

    private MinecraftVersion(int major, int minor, int patch) {
        this.major = major;
        this.minor = minor;
        this.patch = patch;
    }

    public static MinecraftVersion parse(String input) {
        Objects.requireNonNull(input, "input must not be null");
        var matcher = PATTERN.matcher(input.trim());
        if (!matcher.matches()) {
            throw new IllegalArgumentException(
                "Invalid Minecraft version '" + input + "'; expected <major>.<minor>[.<patch>]");
        }
        var patchGroup = matcher.group(3);
        return new MinecraftVersion(
            Integer.parseInt(matcher.group(1)),
            Integer.parseInt(matcher.group(2)),
            patchGroup != null ? Integer.parseInt(patchGroup) : 0);
    }

    /**
     * Classpath resource holding the version this jar was packaged against.
     *
     * <p>Generated by the build from the same {@code minecraftVersion} property
     * the pipeline reads, so the version a distributed server defaults to is the
     * version it was built for — and bumping it stays a one-line property change
     * with no second constant in launcher code to forget.
     */
    public static final String PACKAGED_RESOURCE = "META-INF/veltis/minecraft-version.txt";

    /**
     * The Minecraft version this jar was built for.
     *
     * @throws PatchEngineException when no version was requested and the jar
     *                              carries no packaged one; the message names
     *                              the flag that resolves it
     */
    public static MinecraftVersion launcherDefault(String requested) {
        if (requested != null && !requested.isBlank()) {
            return parse(requested);
        }
        var packaged = packaged();
        if (packaged == null) {
            throw new PatchEngineException(
                "[Veltis] No Minecraft version was requested and this jar does not name one"
                    + "\n  Resource: " + PACKAGED_RESOURCE
                    + "\n  Reason: the jar was assembled without a recorded version, so there"
                    + " is no default to build a runtime for"
                    + "\n  Fix: start the server with --version <major>.<minor>, or set"
                    + " -Dveltismc.minecraftVersion=<major>.<minor>");
        }
        return parse(packaged);
    }

    /**
     * The packaged version, or {@code null} when the resource is absent.
     *
     * <p>Null rather than a hardcoded fallback on purpose. A missing resource
     * means the jar was assembled without one, and guessing a version there
     * would send a server looking for a Minecraft release nobody intended.
     */
    private static String packaged() {
        try (var in = MinecraftVersion.class.getClassLoader()
                .getResourceAsStream(PACKAGED_RESOURCE)) {
            if (in == null) {
                return null;
            }
            var text = new String(in.readAllBytes(), java.nio.charset.StandardCharsets.UTF_8);
            return text.lines().map(String::strip)
                .filter(line -> !line.isEmpty() && !line.startsWith("#"))
                .findFirst()
                .orElse(null);
        } catch (java.io.IOException e) {
            return null;
        }
    }

    public int major() {
        return major;
    }

    public int minor() {
        return minor;
    }

    public int patch() {
        return patch;
    }

    @Override
    public int compareTo(MinecraftVersion other) {
        var majorDiff = Integer.compare(this.major, other.major);
        if (majorDiff != 0) return majorDiff;
        var minorDiff = Integer.compare(this.minor, other.minor);
        if (minorDiff != 0) return minorDiff;
        return Integer.compare(this.patch, other.patch);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (!(obj instanceof MinecraftVersion other)) return false;
        return major == other.major && minor == other.minor && patch == other.patch;
    }

    @Override
    public int hashCode() {
        return Objects.hash(major, minor, patch);
    }

    @Override
    public String toString() {
        return major + "." + minor + (patch > 0 ? "." + patch : "");
    }
}
